package com.battcn.mapper;

import com.battcn.entity.AgentRate;
import com.battcn.entity.AgentRateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgentRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentrate
     *
     * @mbggenerated
     */
    int countByExample(AgentRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentrate
     *
     * @mbggenerated
     */
    int deleteByExample(AgentRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentrate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentrate
     *
     * @mbggenerated
     */
    int insert(AgentRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentrate
     *
     * @mbggenerated
     */
    int insertSelective(AgentRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentrate
     *
     * @mbggenerated
     */
    List<AgentRate> selectByExample(AgentRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentrate
     *
     * @mbggenerated
     */
    AgentRate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentrate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AgentRate record, @Param("example") AgentRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentrate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AgentRate record, @Param("example") AgentRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentrate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AgentRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentrate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AgentRate record);
}