package com.battcn.mapper;

import com.battcn.entity.AgentMerLevel;
import com.battcn.entity.AgentMerLevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgentMerLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentmerlevel
     *
     * @mbggenerated
     */
    int countByExample(AgentMerLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentmerlevel
     *
     * @mbggenerated
     */
    int deleteByExample(AgentMerLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentmerlevel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentmerlevel
     *
     * @mbggenerated
     */
    int insert(AgentMerLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentmerlevel
     *
     * @mbggenerated
     */
    int insertSelective(AgentMerLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentmerlevel
     *
     * @mbggenerated
     */
    List<AgentMerLevel> selectByExample(AgentMerLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentmerlevel
     *
     * @mbggenerated
     */
    AgentMerLevel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentmerlevel
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AgentMerLevel record, @Param("example") AgentMerLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentmerlevel
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AgentMerLevel record, @Param("example") AgentMerLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentmerlevel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AgentMerLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentmerlevel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AgentMerLevel record);
}