package com.battcn.mapper;

import com.battcn.entity.AgentBindArea;
import com.battcn.entity.AgentBindAreaExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AgentBindAreaMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentarea
     *
     * @mbggenerated
     */
    int countByExample(AgentBindAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentarea
     *
     * @mbggenerated
     */
    int deleteByExample(AgentBindAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentarea
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentarea
     *
     * @mbggenerated
     */
    int insert(AgentBindArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentarea
     *
     * @mbggenerated
     */
    int insertSelective(AgentBindArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentarea
     *
     * @mbggenerated
     */
    List<AgentBindArea> selectByExample(AgentBindAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentarea
     *
     * @mbggenerated
     */
    AgentBindArea selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentarea
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AgentBindArea record, @Param("example") AgentBindAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentarea
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AgentBindArea record, @Param("example") AgentBindAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentarea
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AgentBindArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_agentarea
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AgentBindArea record);


//    List<AgentBindArea> querylist(AgentBindArea agentBindArea);
}