package com.battcn.mapper;

import com.battcn.entity.ChannelRate;
import com.battcn.entity.ChannelRateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_channelrate
     *
     * @mbggenerated
     */
    int countByExample(ChannelRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_channelrate
     *
     * @mbggenerated
     */
    int deleteByExample(ChannelRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_channelrate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_channelrate
     *
     * @mbggenerated
     */
    int insert(ChannelRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_channelrate
     *
     * @mbggenerated
     */
    int insertSelective(ChannelRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_channelrate
     *
     * @mbggenerated
     */
    List<ChannelRate> selectByExample(ChannelRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_channelrate
     *
     * @mbggenerated
     */
    ChannelRate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_channelrate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ChannelRate record, @Param("example") ChannelRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_channelrate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ChannelRate record, @Param("example") ChannelRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_channelrate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChannelRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_channelrate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChannelRate record);
    
    List<ChannelRate> selectasile();
    List<ChannelRate> asileGroupByAppId(@Param("appId")String appId);
}