package com.battcn.mapper;

import com.battcn.entity.FixReward;
import com.battcn.entity.FixRewardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FixRewardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_fixed_reward
     *
     * @mbggenerated
     */
    int countByExample(FixRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_fixed_reward
     *
     * @mbggenerated
     */
    int deleteByExample(FixRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_fixed_reward
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_fixed_reward
     *
     * @mbggenerated
     */
    int insert(FixReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_fixed_reward
     *
     * @mbggenerated
     */
    int insertSelective(FixReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_fixed_reward
     *
     * @mbggenerated
     */
    List<FixReward> selectByExample(FixRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_fixed_reward
     *
     * @mbggenerated
     */
    FixReward selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_fixed_reward
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FixReward record, @Param("example") FixRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_fixed_reward
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FixReward record, @Param("example") FixRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_fixed_reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FixReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_fixed_reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FixReward record);
}