package com.battcn.mapper;

import com.battcn.entity.HYUserForm;
import com.battcn.entity.HYUserFormExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HYUserFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    int countByExample(HYUserFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    int deleteByExample(HYUserFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    int insert(HYUserForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    int insertSelective(HYUserForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    List<HYUserForm> selectByExample(HYUserFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    HYUserForm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HYUserForm record, @Param("example") HYUserFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HYUserForm record, @Param("example") HYUserFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HYUserForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HYUserForm record);
}