package com.battcn.mapper;

import com.battcn.entity.MerRateRecord;
import com.battcn.entity.MerRateRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MerRateRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantsrate_record
     *
     * @mbggenerated
     */
    int countByExample(MerRateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantsrate_record
     *
     * @mbggenerated
     */
    int deleteByExample(MerRateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantsrate_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantsrate_record
     *
     * @mbggenerated
     */
    int insert(MerRateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantsrate_record
     *
     * @mbggenerated
     */
    int insertSelective(MerRateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantsrate_record
     *
     * @mbggenerated
     */
    List<MerRateRecord> selectByExample(MerRateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantsrate_record
     *
     * @mbggenerated
     */
    MerRateRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantsrate_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MerRateRecord record, @Param("example") MerRateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantsrate_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MerRateRecord record, @Param("example") MerRateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantsrate_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MerRateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchantsrate_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MerRateRecord record);
}