package com.battcn.mapper;

import com.battcn.entity.PaymentNum;
import com.battcn.entity.PaymentNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    int countByExample(PaymentNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    int deleteByExample(PaymentNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    int insert(PaymentNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    int insertSelective(PaymentNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    List<PaymentNum> selectByExample(PaymentNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    PaymentNum selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PaymentNum record, @Param("example") PaymentNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PaymentNum record, @Param("example") PaymentNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymentNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentNum record);
}