package com.battcn.mapper;

import com.battcn.entity.Profit;
import com.battcn.entity.ProfitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProfitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_profit
     *
     * @mbggenerated
     */
    int countByExample(ProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_profit
     *
     * @mbggenerated
     */
    int deleteByExample(ProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_profit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_profit
     *
     * @mbggenerated
     */
    int insert(Profit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_profit
     *
     * @mbggenerated
     */
    int insertSelective(Profit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_profit
     *
     * @mbggenerated
     */
    List<Profit> selectByExample(ProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_profit
     *
     * @mbggenerated
     */
    Profit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_profit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Profit record, @Param("example") ProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_profit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Profit record, @Param("example") ProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_profit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Profit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_profit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Profit record);
}