package com.battcn.mapper;

import com.battcn.entity.Rates;
import com.battcn.entity.RatesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_rates
     *
     * @mbggenerated
     */
    int countByExample(RatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_rates
     *
     * @mbggenerated
     */
    int deleteByExample(RatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_rates
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_rates
     *
     * @mbggenerated
     */
    int insert(Rates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_rates
     *
     * @mbggenerated
     */
    int insertSelective(Rates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_rates
     *
     * @mbggenerated
     */
    List<Rates> selectByExample(RatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_rates
     *
     * @mbggenerated
     */
    Rates selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_rates
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Rates record, @Param("example") RatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_rates
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Rates record, @Param("example") RatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_rates
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Rates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_rates
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Rates record);
}