package com.battcn.mapper;

import com.battcn.entity.Subsidy;
import com.battcn.entity.SubsidyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubsidyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    int countByExample(SubsidyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    int deleteByExample(SubsidyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    int insert(Subsidy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    int insertSelective(Subsidy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    List<Subsidy> selectByExample(SubsidyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    Subsidy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Subsidy record, @Param("example") SubsidyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Subsidy record, @Param("example") SubsidyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Subsidy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Subsidy record);
}