package com.battcn.mapper;

import com.battcn.entity.SureRecord;
import com.battcn.entity.SureRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SureRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_surerecord
     *
     * @mbggenerated
     */
    int countByExample(SureRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_surerecord
     *
     * @mbggenerated
     */
    int deleteByExample(SureRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_surerecord
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_surerecord
     *
     * @mbggenerated
     */
    int insert(SureRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_surerecord
     *
     * @mbggenerated
     */
    int insertSelective(SureRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_surerecord
     *
     * @mbggenerated
     */
    List<SureRecord> selectByExample(SureRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_surerecord
     *
     * @mbggenerated
     */
    SureRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_surerecord
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SureRecord record, @Param("example") SureRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_surerecord
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SureRecord record, @Param("example") SureRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_surerecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SureRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_surerecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SureRecord record);
}