package com.battcn.entity;

public class AgentMerLevel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_agentmerlevel.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_agentmerlevel.levelName
     *
     * @mbggenerated
     */
    private String levelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_agentmerlevel.levelLogo
     *
     * @mbggenerated
     */
    private String levellogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_agentmerlevel.levelBCard
     *
     * @mbggenerated
     */
    private String levelbcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_agentmerlevel.levelWeight
     *
     * @mbggenerated
     */
    private Long levelweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_agentmerlevel.merLevel
     *
     * @mbggenerated
     */
    private String merlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_agentmerlevel.agentOrNot
     *
     * @mbggenerated
     */
    private String agentornot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_agentmerlevel.agentStatus
     *
     * @mbggenerated
     */
    private String agentstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_agentmerlevel.agentId
     *
     * @mbggenerated
     */
    private String agentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_agentmerlevel.showOrNot
     *
     * @mbggenerated
     */
    private String showornot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_agentmerlevel.funcExplain
     *
     * @mbggenerated
     */
    private String funcexplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_agentmerlevel.usableModule
     *
     * @mbggenerated
     */
    private String usablemodule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_agentmerlevel.id
     *
     * @return the value of t_mp_agentmerlevel.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_agentmerlevel.id
     *
     * @param id the value for t_mp_agentmerlevel.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_agentmerlevel.levelName
     *
     * @return the value of t_mp_agentmerlevel.levelName
     *
     * @mbggenerated
     */
    public String getLevelname() {
        return levelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_agentmerlevel.levelName
     *
     * @param levelname the value for t_mp_agentmerlevel.levelName
     *
     * @mbggenerated
     */
    public void setLevelname(String levelname) {
        this.levelname = levelname == null ? null : levelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_agentmerlevel.levelLogo
     *
     * @return the value of t_mp_agentmerlevel.levelLogo
     *
     * @mbggenerated
     */
    public String getLevellogo() {
        return levellogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_agentmerlevel.levelLogo
     *
     * @param levellogo the value for t_mp_agentmerlevel.levelLogo
     *
     * @mbggenerated
     */
    public void setLevellogo(String levellogo) {
        this.levellogo = levellogo == null ? null : levellogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_agentmerlevel.levelBCard
     *
     * @return the value of t_mp_agentmerlevel.levelBCard
     *
     * @mbggenerated
     */
    public String getLevelbcard() {
        return levelbcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_agentmerlevel.levelBCard
     *
     * @param levelbcard the value for t_mp_agentmerlevel.levelBCard
     *
     * @mbggenerated
     */
    public void setLevelbcard(String levelbcard) {
        this.levelbcard = levelbcard == null ? null : levelbcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_agentmerlevel.levelWeight
     *
     * @return the value of t_mp_agentmerlevel.levelWeight
     *
     * @mbggenerated
     */
    public Long getLevelweight() {
        return levelweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_agentmerlevel.levelWeight
     *
     * @param levelweight the value for t_mp_agentmerlevel.levelWeight
     *
     * @mbggenerated
     */
    public void setLevelweight(Long levelweight) {
        this.levelweight = levelweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_agentmerlevel.merLevel
     *
     * @return the value of t_mp_agentmerlevel.merLevel
     *
     * @mbggenerated
     */
    public String getMerlevel() {
        return merlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_agentmerlevel.merLevel
     *
     * @param merlevel the value for t_mp_agentmerlevel.merLevel
     *
     * @mbggenerated
     */
    public void setMerlevel(String merlevel) {
        this.merlevel = merlevel == null ? null : merlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_agentmerlevel.agentOrNot
     *
     * @return the value of t_mp_agentmerlevel.agentOrNot
     *
     * @mbggenerated
     */
    public String getAgentornot() {
        return agentornot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_agentmerlevel.agentOrNot
     *
     * @param agentornot the value for t_mp_agentmerlevel.agentOrNot
     *
     * @mbggenerated
     */
    public void setAgentornot(String agentornot) {
        this.agentornot = agentornot == null ? null : agentornot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_agentmerlevel.agentStatus
     *
     * @return the value of t_mp_agentmerlevel.agentStatus
     *
     * @mbggenerated
     */
    public String getAgentstatus() {
        return agentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_agentmerlevel.agentStatus
     *
     * @param agentstatus the value for t_mp_agentmerlevel.agentStatus
     *
     * @mbggenerated
     */
    public void setAgentstatus(String agentstatus) {
        this.agentstatus = agentstatus == null ? null : agentstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_agentmerlevel.agentId
     *
     * @return the value of t_mp_agentmerlevel.agentId
     *
     * @mbggenerated
     */
    public String getAgentid() {
        return agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_agentmerlevel.agentId
     *
     * @param agentid the value for t_mp_agentmerlevel.agentId
     *
     * @mbggenerated
     */
    public void setAgentid(String agentid) {
        this.agentid = agentid == null ? null : agentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_agentmerlevel.showOrNot
     *
     * @return the value of t_mp_agentmerlevel.showOrNot
     *
     * @mbggenerated
     */
    public String getShowornot() {
        return showornot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_agentmerlevel.showOrNot
     *
     * @param showornot the value for t_mp_agentmerlevel.showOrNot
     *
     * @mbggenerated
     */
    public void setShowornot(String showornot) {
        this.showornot = showornot == null ? null : showornot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_agentmerlevel.funcExplain
     *
     * @return the value of t_mp_agentmerlevel.funcExplain
     *
     * @mbggenerated
     */
    public String getFuncexplain() {
        return funcexplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_agentmerlevel.funcExplain
     *
     * @param funcexplain the value for t_mp_agentmerlevel.funcExplain
     *
     * @mbggenerated
     */
    public void setFuncexplain(String funcexplain) {
        this.funcexplain = funcexplain == null ? null : funcexplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_agentmerlevel.usableModule
     *
     * @return the value of t_mp_agentmerlevel.usableModule
     *
     * @mbggenerated
     */
    public String getUsablemodule() {
        return usablemodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_agentmerlevel.usableModule
     *
     * @param usablemodule the value for t_mp_agentmerlevel.usableModule
     *
     * @mbggenerated
     */
    public void setUsablemodule(String usablemodule) {
        this.usablemodule = usablemodule == null ? null : usablemodule.trim();
    }
}