package com.battcn.entity;

public class EnjoyOrNot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column num_equity_enjoy.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column num_equity_enjoy.minOrNot
     *
     * @mbggenerated
     */
    private String minornot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column num_equity_enjoy.maxOrNot
     *
     * @mbggenerated
     */
    private String maxornot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column num_equity_enjoy.id
     *
     * @return the value of num_equity_enjoy.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column num_equity_enjoy.id
     *
     * @param id the value for num_equity_enjoy.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column num_equity_enjoy.minOrNot
     *
     * @return the value of num_equity_enjoy.minOrNot
     *
     * @mbggenerated
     */
    public String getMinornot() {
        return minornot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column num_equity_enjoy.minOrNot
     *
     * @param minornot the value for num_equity_enjoy.minOrNot
     *
     * @mbggenerated
     */
    public void setMinornot(String minornot) {
        this.minornot = minornot == null ? null : minornot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column num_equity_enjoy.maxOrNot
     *
     * @return the value of num_equity_enjoy.maxOrNot
     *
     * @mbggenerated
     */
    public String getMaxornot() {
        return maxornot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column num_equity_enjoy.maxOrNot
     *
     * @param maxornot the value for num_equity_enjoy.maxOrNot
     *
     * @mbggenerated
     */
    public void setMaxornot(String maxornot) {
        this.maxornot = maxornot == null ? null : maxornot.trim();
    }
}