package com.battcn.entity;

import java.math.BigDecimal;
/*
 * 实际上就是t_mp-merchants用户表
 * 取这个名字是为了方便区分
 * 这个实体类是用来计算报表的
 */
public class HYUserForm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.merChantId
     *
     * @mbggenerated
     */
    private String merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.merName
     *
     * @mbggenerated
     */
    private String mername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.merMp
     *
     * @mbggenerated
     */
    private String mermp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.certNo
     *
     * @mbggenerated
     */
    private String certno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.merStat
     *
     * @mbggenerated
     */
    private String merstat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.identifying
     *
     * @mbggenerated
     */
    private String identifying;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.merChantFee
     *
     * @mbggenerated
     */
    private String merchantfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.generationFee
     *
     * @mbggenerated
     */
    private String generationfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.generationFeeRepayment
     *
     * @mbggenerated
     */
    private String generationfeerepayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.agentStatus
     *
     * @mbggenerated
     */
    private String agentstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.agentId
     *
     * @mbggenerated
     */
    private String agentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.institutionId
     *
     * @mbggenerated
     */
    private String institutionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.merType
     *
     * @mbggenerated
     */
    private String mertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.oneMerId
     *
     * @mbggenerated
     */
    private String onemerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.twoMerId
     *
     * @mbggenerated
     */
    private String twomerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.threeMerId
     *
     * @mbggenerated
     */
    private String threemerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.frozen
     *
     * @mbggenerated
     */
    private String frozen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.faceImgUrl
     *
     * @mbggenerated
     */
    private String faceimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.regDate
     *
     * @mbggenerated
     */
    private String regdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.merStatTime
     *
     * @mbggenerated
     */
    private String merstattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.statusDate
     *
     * @mbggenerated
     */
    private String statusdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.startDate
     *
     * @mbggenerated
     */
    private String startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.finishDate
     *
     * @mbggenerated
     */
    private String finishdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.appId
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.appName
     *
     * @mbggenerated
     */
    private String appname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.balanceProfit
     *
     * @mbggenerated
     */
    private BigDecimal balanceprofit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.balanceFrozen
     *
     * @mbggenerated
     */
    private BigDecimal balancefrozen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.balanceProfitFrozen
     *
     * @mbggenerated
     */
    private BigDecimal balanceprofitfrozen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_merchants.used
     *
     * @mbggenerated
     */
    private String used;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.id
     *
     * @return the value of t_mp_merchants.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.id
     *
     * @param id the value for t_mp_merchants.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.merChantId
     *
     * @return the value of t_mp_merchants.merChantId
     *
     * @mbggenerated
     */
    public String getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.merChantId
     *
     * @param merchantid the value for t_mp_merchants.merChantId
     *
     * @mbggenerated
     */
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid == null ? null : merchantid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.merName
     *
     * @return the value of t_mp_merchants.merName
     *
     * @mbggenerated
     */
    public String getMername() {
        return mername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.merName
     *
     * @param mername the value for t_mp_merchants.merName
     *
     * @mbggenerated
     */
    public void setMername(String mername) {
        this.mername = mername == null ? null : mername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.merMp
     *
     * @return the value of t_mp_merchants.merMp
     *
     * @mbggenerated
     */
    public String getMermp() {
        return mermp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.merMp
     *
     * @param mermp the value for t_mp_merchants.merMp
     *
     * @mbggenerated
     */
    public void setMermp(String mermp) {
        this.mermp = mermp == null ? null : mermp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.certNo
     *
     * @return the value of t_mp_merchants.certNo
     *
     * @mbggenerated
     */
    public String getCertno() {
        return certno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.certNo
     *
     * @param certno the value for t_mp_merchants.certNo
     *
     * @mbggenerated
     */
    public void setCertno(String certno) {
        this.certno = certno == null ? null : certno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.merStat
     *
     * @return the value of t_mp_merchants.merStat
     *
     * @mbggenerated
     */
    public String getMerstat() {
        return merstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.merStat
     *
     * @param merstat the value for t_mp_merchants.merStat
     *
     * @mbggenerated
     */
    public void setMerstat(String merstat) {
        this.merstat = merstat == null ? null : merstat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.identifying
     *
     * @return the value of t_mp_merchants.identifying
     *
     * @mbggenerated
     */
    public String getIdentifying() {
        return identifying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.identifying
     *
     * @param identifying the value for t_mp_merchants.identifying
     *
     * @mbggenerated
     */
    public void setIdentifying(String identifying) {
        this.identifying = identifying == null ? null : identifying.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.merChantFee
     *
     * @return the value of t_mp_merchants.merChantFee
     *
     * @mbggenerated
     */
    public String getMerchantfee() {
        return merchantfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.merChantFee
     *
     * @param merchantfee the value for t_mp_merchants.merChantFee
     *
     * @mbggenerated
     */
    public void setMerchantfee(String merchantfee) {
        this.merchantfee = merchantfee == null ? null : merchantfee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.generationFee
     *
     * @return the value of t_mp_merchants.generationFee
     *
     * @mbggenerated
     */
    public String getGenerationfee() {
        return generationfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.generationFee
     *
     * @param generationfee the value for t_mp_merchants.generationFee
     *
     * @mbggenerated
     */
    public void setGenerationfee(String generationfee) {
        this.generationfee = generationfee == null ? null : generationfee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.generationFeeRepayment
     *
     * @return the value of t_mp_merchants.generationFeeRepayment
     *
     * @mbggenerated
     */
    public String getGenerationfeerepayment() {
        return generationfeerepayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.generationFeeRepayment
     *
     * @param generationfeerepayment the value for t_mp_merchants.generationFeeRepayment
     *
     * @mbggenerated
     */
    public void setGenerationfeerepayment(String generationfeerepayment) {
        this.generationfeerepayment = generationfeerepayment == null ? null : generationfeerepayment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.status
     *
     * @return the value of t_mp_merchants.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.status
     *
     * @param status the value for t_mp_merchants.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.agentStatus
     *
     * @return the value of t_mp_merchants.agentStatus
     *
     * @mbggenerated
     */
    public String getAgentstatus() {
        return agentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.agentStatus
     *
     * @param agentstatus the value for t_mp_merchants.agentStatus
     *
     * @mbggenerated
     */
    public void setAgentstatus(String agentstatus) {
        this.agentstatus = agentstatus == null ? null : agentstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.agentId
     *
     * @return the value of t_mp_merchants.agentId
     *
     * @mbggenerated
     */
    public String getAgentid() {
        return agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.agentId
     *
     * @param agentid the value for t_mp_merchants.agentId
     *
     * @mbggenerated
     */
    public void setAgentid(String agentid) {
        this.agentid = agentid == null ? null : agentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.institutionId
     *
     * @return the value of t_mp_merchants.institutionId
     *
     * @mbggenerated
     */
    public String getInstitutionid() {
        return institutionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.institutionId
     *
     * @param institutionid the value for t_mp_merchants.institutionId
     *
     * @mbggenerated
     */
    public void setInstitutionid(String institutionid) {
        this.institutionid = institutionid == null ? null : institutionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.merType
     *
     * @return the value of t_mp_merchants.merType
     *
     * @mbggenerated
     */
    public String getMertype() {
        return mertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.merType
     *
     * @param mertype the value for t_mp_merchants.merType
     *
     * @mbggenerated
     */
    public void setMertype(String mertype) {
        this.mertype = mertype == null ? null : mertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.oneMerId
     *
     * @return the value of t_mp_merchants.oneMerId
     *
     * @mbggenerated
     */
    public String getOnemerid() {
        return onemerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.oneMerId
     *
     * @param onemerid the value for t_mp_merchants.oneMerId
     *
     * @mbggenerated
     */
    public void setOnemerid(String onemerid) {
        this.onemerid = onemerid == null ? null : onemerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.twoMerId
     *
     * @return the value of t_mp_merchants.twoMerId
     *
     * @mbggenerated
     */
    public String getTwomerid() {
        return twomerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.twoMerId
     *
     * @param twomerid the value for t_mp_merchants.twoMerId
     *
     * @mbggenerated
     */
    public void setTwomerid(String twomerid) {
        this.twomerid = twomerid == null ? null : twomerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.threeMerId
     *
     * @return the value of t_mp_merchants.threeMerId
     *
     * @mbggenerated
     */
    public String getThreemerid() {
        return threemerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.threeMerId
     *
     * @param threemerid the value for t_mp_merchants.threeMerId
     *
     * @mbggenerated
     */
    public void setThreemerid(String threemerid) {
        this.threemerid = threemerid == null ? null : threemerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.frozen
     *
     * @return the value of t_mp_merchants.frozen
     *
     * @mbggenerated
     */
    public String getFrozen() {
        return frozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.frozen
     *
     * @param frozen the value for t_mp_merchants.frozen
     *
     * @mbggenerated
     */
    public void setFrozen(String frozen) {
        this.frozen = frozen == null ? null : frozen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.faceImgUrl
     *
     * @return the value of t_mp_merchants.faceImgUrl
     *
     * @mbggenerated
     */
    public String getFaceimgurl() {
        return faceimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.faceImgUrl
     *
     * @param faceimgurl the value for t_mp_merchants.faceImgUrl
     *
     * @mbggenerated
     */
    public void setFaceimgurl(String faceimgurl) {
        this.faceimgurl = faceimgurl == null ? null : faceimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.regDate
     *
     * @return the value of t_mp_merchants.regDate
     *
     * @mbggenerated
     */
    public String getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.regDate
     *
     * @param regdate the value for t_mp_merchants.regDate
     *
     * @mbggenerated
     */
    public void setRegdate(String regdate) {
        this.regdate = regdate == null ? null : regdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.merStatTime
     *
     * @return the value of t_mp_merchants.merStatTime
     *
     * @mbggenerated
     */
    public String getMerstattime() {
        return merstattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.merStatTime
     *
     * @param merstattime the value for t_mp_merchants.merStatTime
     *
     * @mbggenerated
     */
    public void setMerstattime(String merstattime) {
        this.merstattime = merstattime == null ? null : merstattime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.statusDate
     *
     * @return the value of t_mp_merchants.statusDate
     *
     * @mbggenerated
     */
    public String getStatusdate() {
        return statusdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.statusDate
     *
     * @param statusdate the value for t_mp_merchants.statusDate
     *
     * @mbggenerated
     */
    public void setStatusdate(String statusdate) {
        this.statusdate = statusdate == null ? null : statusdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.startDate
     *
     * @return the value of t_mp_merchants.startDate
     *
     * @mbggenerated
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.startDate
     *
     * @param startdate the value for t_mp_merchants.startDate
     *
     * @mbggenerated
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate == null ? null : startdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.finishDate
     *
     * @return the value of t_mp_merchants.finishDate
     *
     * @mbggenerated
     */
    public String getFinishdate() {
        return finishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.finishDate
     *
     * @param finishdate the value for t_mp_merchants.finishDate
     *
     * @mbggenerated
     */
    public void setFinishdate(String finishdate) {
        this.finishdate = finishdate == null ? null : finishdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.appId
     *
     * @return the value of t_mp_merchants.appId
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.appId
     *
     * @param appid the value for t_mp_merchants.appId
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.appName
     *
     * @return the value of t_mp_merchants.appName
     *
     * @mbggenerated
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.appName
     *
     * @param appname the value for t_mp_merchants.appName
     *
     * @mbggenerated
     */
    public void setAppname(String appname) {
        this.appname = appname == null ? null : appname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.balance
     *
     * @return the value of t_mp_merchants.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.balance
     *
     * @param balance the value for t_mp_merchants.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.balanceProfit
     *
     * @return the value of t_mp_merchants.balanceProfit
     *
     * @mbggenerated
     */
    public BigDecimal getBalanceprofit() {
        return balanceprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.balanceProfit
     *
     * @param balanceprofit the value for t_mp_merchants.balanceProfit
     *
     * @mbggenerated
     */
    public void setBalanceprofit(BigDecimal balanceprofit) {
        this.balanceprofit = balanceprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.balanceFrozen
     *
     * @return the value of t_mp_merchants.balanceFrozen
     *
     * @mbggenerated
     */
    public BigDecimal getBalancefrozen() {
        return balancefrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.balanceFrozen
     *
     * @param balancefrozen the value for t_mp_merchants.balanceFrozen
     *
     * @mbggenerated
     */
    public void setBalancefrozen(BigDecimal balancefrozen) {
        this.balancefrozen = balancefrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.balanceProfitFrozen
     *
     * @return the value of t_mp_merchants.balanceProfitFrozen
     *
     * @mbggenerated
     */
    public BigDecimal getBalanceprofitfrozen() {
        return balanceprofitfrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.balanceProfitFrozen
     *
     * @param balanceprofitfrozen the value for t_mp_merchants.balanceProfitFrozen
     *
     * @mbggenerated
     */
    public void setBalanceprofitfrozen(BigDecimal balanceprofitfrozen) {
        this.balanceprofitfrozen = balanceprofitfrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.remarks
     *
     * @return the value of t_mp_merchants.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.remarks
     *
     * @param remarks the value for t_mp_merchants.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_merchants.used
     *
     * @return the value of t_mp_merchants.used
     *
     * @mbggenerated
     */
    public String getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_merchants.used
     *
     * @param used the value for t_mp_merchants.used
     *
     * @mbggenerated
     */
    public void setUsed(String used) {
        this.used = used == null ? null : used.trim();
    }
}