package com.battcn.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class HYUserFormExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    public HYUserFormExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMerchantidIsNull() {
            addCriterion("merChantId is null");
            return (Criteria) this;
        }

        public Criteria andMerchantidIsNotNull() {
            addCriterion("merChantId is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantidEqualTo(String value) {
            addCriterion("merChantId =", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidNotEqualTo(String value) {
            addCriterion("merChantId <>", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidGreaterThan(String value) {
            addCriterion("merChantId >", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidGreaterThanOrEqualTo(String value) {
            addCriterion("merChantId >=", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidLessThan(String value) {
            addCriterion("merChantId <", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidLessThanOrEqualTo(String value) {
            addCriterion("merChantId <=", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidLike(String value) {
            addCriterion("merChantId like", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidNotLike(String value) {
            addCriterion("merChantId not like", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidIn(List<String> values) {
            addCriterion("merChantId in", values, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidNotIn(List<String> values) {
            addCriterion("merChantId not in", values, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidBetween(String value1, String value2) {
            addCriterion("merChantId between", value1, value2, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidNotBetween(String value1, String value2) {
            addCriterion("merChantId not between", value1, value2, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMernameIsNull() {
            addCriterion("merName is null");
            return (Criteria) this;
        }

        public Criteria andMernameIsNotNull() {
            addCriterion("merName is not null");
            return (Criteria) this;
        }

        public Criteria andMernameEqualTo(String value) {
            addCriterion("merName =", value, "mername");
            return (Criteria) this;
        }

        public Criteria andMernameNotEqualTo(String value) {
            addCriterion("merName <>", value, "mername");
            return (Criteria) this;
        }

        public Criteria andMernameGreaterThan(String value) {
            addCriterion("merName >", value, "mername");
            return (Criteria) this;
        }

        public Criteria andMernameGreaterThanOrEqualTo(String value) {
            addCriterion("merName >=", value, "mername");
            return (Criteria) this;
        }

        public Criteria andMernameLessThan(String value) {
            addCriterion("merName <", value, "mername");
            return (Criteria) this;
        }

        public Criteria andMernameLessThanOrEqualTo(String value) {
            addCriterion("merName <=", value, "mername");
            return (Criteria) this;
        }

        public Criteria andMernameLike(String value) {
            addCriterion("merName like", value, "mername");
            return (Criteria) this;
        }

        public Criteria andMernameNotLike(String value) {
            addCriterion("merName not like", value, "mername");
            return (Criteria) this;
        }

        public Criteria andMernameIn(List<String> values) {
            addCriterion("merName in", values, "mername");
            return (Criteria) this;
        }

        public Criteria andMernameNotIn(List<String> values) {
            addCriterion("merName not in", values, "mername");
            return (Criteria) this;
        }

        public Criteria andMernameBetween(String value1, String value2) {
            addCriterion("merName between", value1, value2, "mername");
            return (Criteria) this;
        }

        public Criteria andMernameNotBetween(String value1, String value2) {
            addCriterion("merName not between", value1, value2, "mername");
            return (Criteria) this;
        }

        public Criteria andMermpIsNull() {
            addCriterion("merMp is null");
            return (Criteria) this;
        }

        public Criteria andMermpIsNotNull() {
            addCriterion("merMp is not null");
            return (Criteria) this;
        }

        public Criteria andMermpEqualTo(String value) {
            addCriterion("merMp =", value, "mermp");
            return (Criteria) this;
        }

        public Criteria andMermpNotEqualTo(String value) {
            addCriterion("merMp <>", value, "mermp");
            return (Criteria) this;
        }

        public Criteria andMermpGreaterThan(String value) {
            addCriterion("merMp >", value, "mermp");
            return (Criteria) this;
        }

        public Criteria andMermpGreaterThanOrEqualTo(String value) {
            addCriterion("merMp >=", value, "mermp");
            return (Criteria) this;
        }

        public Criteria andMermpLessThan(String value) {
            addCriterion("merMp <", value, "mermp");
            return (Criteria) this;
        }

        public Criteria andMermpLessThanOrEqualTo(String value) {
            addCriterion("merMp <=", value, "mermp");
            return (Criteria) this;
        }

        public Criteria andMermpLike(String value) {
            addCriterion("merMp like", value, "mermp");
            return (Criteria) this;
        }

        public Criteria andMermpNotLike(String value) {
            addCriterion("merMp not like", value, "mermp");
            return (Criteria) this;
        }

        public Criteria andMermpIn(List<String> values) {
            addCriterion("merMp in", values, "mermp");
            return (Criteria) this;
        }

        public Criteria andMermpNotIn(List<String> values) {
            addCriterion("merMp not in", values, "mermp");
            return (Criteria) this;
        }

        public Criteria andMermpBetween(String value1, String value2) {
            addCriterion("merMp between", value1, value2, "mermp");
            return (Criteria) this;
        }

        public Criteria andMermpNotBetween(String value1, String value2) {
            addCriterion("merMp not between", value1, value2, "mermp");
            return (Criteria) this;
        }

        public Criteria andCertnoIsNull() {
            addCriterion("certNo is null");
            return (Criteria) this;
        }

        public Criteria andCertnoIsNotNull() {
            addCriterion("certNo is not null");
            return (Criteria) this;
        }

        public Criteria andCertnoEqualTo(String value) {
            addCriterion("certNo =", value, "certno");
            return (Criteria) this;
        }

        public Criteria andCertnoNotEqualTo(String value) {
            addCriterion("certNo <>", value, "certno");
            return (Criteria) this;
        }

        public Criteria andCertnoGreaterThan(String value) {
            addCriterion("certNo >", value, "certno");
            return (Criteria) this;
        }

        public Criteria andCertnoGreaterThanOrEqualTo(String value) {
            addCriterion("certNo >=", value, "certno");
            return (Criteria) this;
        }

        public Criteria andCertnoLessThan(String value) {
            addCriterion("certNo <", value, "certno");
            return (Criteria) this;
        }

        public Criteria andCertnoLessThanOrEqualTo(String value) {
            addCriterion("certNo <=", value, "certno");
            return (Criteria) this;
        }

        public Criteria andCertnoLike(String value) {
            addCriterion("certNo like", value, "certno");
            return (Criteria) this;
        }

        public Criteria andCertnoNotLike(String value) {
            addCriterion("certNo not like", value, "certno");
            return (Criteria) this;
        }

        public Criteria andCertnoIn(List<String> values) {
            addCriterion("certNo in", values, "certno");
            return (Criteria) this;
        }

        public Criteria andCertnoNotIn(List<String> values) {
            addCriterion("certNo not in", values, "certno");
            return (Criteria) this;
        }

        public Criteria andCertnoBetween(String value1, String value2) {
            addCriterion("certNo between", value1, value2, "certno");
            return (Criteria) this;
        }

        public Criteria andCertnoNotBetween(String value1, String value2) {
            addCriterion("certNo not between", value1, value2, "certno");
            return (Criteria) this;
        }

        public Criteria andMerstatIsNull() {
            addCriterion("merStat is null");
            return (Criteria) this;
        }

        public Criteria andMerstatIsNotNull() {
            addCriterion("merStat is not null");
            return (Criteria) this;
        }

        public Criteria andMerstatEqualTo(String value) {
            addCriterion("merStat =", value, "merstat");
            return (Criteria) this;
        }

        public Criteria andMerstatNotEqualTo(String value) {
            addCriterion("merStat <>", value, "merstat");
            return (Criteria) this;
        }

        public Criteria andMerstatGreaterThan(String value) {
            addCriterion("merStat >", value, "merstat");
            return (Criteria) this;
        }

        public Criteria andMerstatGreaterThanOrEqualTo(String value) {
            addCriterion("merStat >=", value, "merstat");
            return (Criteria) this;
        }

        public Criteria andMerstatLessThan(String value) {
            addCriterion("merStat <", value, "merstat");
            return (Criteria) this;
        }

        public Criteria andMerstatLessThanOrEqualTo(String value) {
            addCriterion("merStat <=", value, "merstat");
            return (Criteria) this;
        }

        public Criteria andMerstatLike(String value) {
            addCriterion("merStat like", value, "merstat");
            return (Criteria) this;
        }

        public Criteria andMerstatNotLike(String value) {
            addCriterion("merStat not like", value, "merstat");
            return (Criteria) this;
        }

        public Criteria andMerstatIn(List<String> values) {
            addCriterion("merStat in", values, "merstat");
            return (Criteria) this;
        }

        public Criteria andMerstatNotIn(List<String> values) {
            addCriterion("merStat not in", values, "merstat");
            return (Criteria) this;
        }

        public Criteria andMerstatBetween(String value1, String value2) {
            addCriterion("merStat between", value1, value2, "merstat");
            return (Criteria) this;
        }

        public Criteria andMerstatNotBetween(String value1, String value2) {
            addCriterion("merStat not between", value1, value2, "merstat");
            return (Criteria) this;
        }

        public Criteria andIdentifyingIsNull() {
            addCriterion("identifying is null");
            return (Criteria) this;
        }

        public Criteria andIdentifyingIsNotNull() {
            addCriterion("identifying is not null");
            return (Criteria) this;
        }

        public Criteria andIdentifyingEqualTo(String value) {
            addCriterion("identifying =", value, "identifying");
            return (Criteria) this;
        }

        public Criteria andIdentifyingNotEqualTo(String value) {
            addCriterion("identifying <>", value, "identifying");
            return (Criteria) this;
        }

        public Criteria andIdentifyingGreaterThan(String value) {
            addCriterion("identifying >", value, "identifying");
            return (Criteria) this;
        }

        public Criteria andIdentifyingGreaterThanOrEqualTo(String value) {
            addCriterion("identifying >=", value, "identifying");
            return (Criteria) this;
        }

        public Criteria andIdentifyingLessThan(String value) {
            addCriterion("identifying <", value, "identifying");
            return (Criteria) this;
        }

        public Criteria andIdentifyingLessThanOrEqualTo(String value) {
            addCriterion("identifying <=", value, "identifying");
            return (Criteria) this;
        }

        public Criteria andIdentifyingLike(String value) {
            addCriterion("identifying like", value, "identifying");
            return (Criteria) this;
        }

        public Criteria andIdentifyingNotLike(String value) {
            addCriterion("identifying not like", value, "identifying");
            return (Criteria) this;
        }

        public Criteria andIdentifyingIn(List<String> values) {
            addCriterion("identifying in", values, "identifying");
            return (Criteria) this;
        }

        public Criteria andIdentifyingNotIn(List<String> values) {
            addCriterion("identifying not in", values, "identifying");
            return (Criteria) this;
        }

        public Criteria andIdentifyingBetween(String value1, String value2) {
            addCriterion("identifying between", value1, value2, "identifying");
            return (Criteria) this;
        }

        public Criteria andIdentifyingNotBetween(String value1, String value2) {
            addCriterion("identifying not between", value1, value2, "identifying");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeIsNull() {
            addCriterion("merChantFee is null");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeIsNotNull() {
            addCriterion("merChantFee is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeEqualTo(String value) {
            addCriterion("merChantFee =", value, "merchantfee");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeNotEqualTo(String value) {
            addCriterion("merChantFee <>", value, "merchantfee");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeGreaterThan(String value) {
            addCriterion("merChantFee >", value, "merchantfee");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeGreaterThanOrEqualTo(String value) {
            addCriterion("merChantFee >=", value, "merchantfee");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeLessThan(String value) {
            addCriterion("merChantFee <", value, "merchantfee");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeLessThanOrEqualTo(String value) {
            addCriterion("merChantFee <=", value, "merchantfee");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeLike(String value) {
            addCriterion("merChantFee like", value, "merchantfee");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeNotLike(String value) {
            addCriterion("merChantFee not like", value, "merchantfee");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeIn(List<String> values) {
            addCriterion("merChantFee in", values, "merchantfee");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeNotIn(List<String> values) {
            addCriterion("merChantFee not in", values, "merchantfee");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeBetween(String value1, String value2) {
            addCriterion("merChantFee between", value1, value2, "merchantfee");
            return (Criteria) this;
        }

        public Criteria andMerchantfeeNotBetween(String value1, String value2) {
            addCriterion("merChantFee not between", value1, value2, "merchantfee");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeIsNull() {
            addCriterion("generationFee is null");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeIsNotNull() {
            addCriterion("generationFee is not null");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeEqualTo(String value) {
            addCriterion("generationFee =", value, "generationfee");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeNotEqualTo(String value) {
            addCriterion("generationFee <>", value, "generationfee");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeGreaterThan(String value) {
            addCriterion("generationFee >", value, "generationfee");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeGreaterThanOrEqualTo(String value) {
            addCriterion("generationFee >=", value, "generationfee");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeLessThan(String value) {
            addCriterion("generationFee <", value, "generationfee");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeLessThanOrEqualTo(String value) {
            addCriterion("generationFee <=", value, "generationfee");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeLike(String value) {
            addCriterion("generationFee like", value, "generationfee");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeNotLike(String value) {
            addCriterion("generationFee not like", value, "generationfee");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeIn(List<String> values) {
            addCriterion("generationFee in", values, "generationfee");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeNotIn(List<String> values) {
            addCriterion("generationFee not in", values, "generationfee");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeBetween(String value1, String value2) {
            addCriterion("generationFee between", value1, value2, "generationfee");
            return (Criteria) this;
        }

        public Criteria andGenerationfeeNotBetween(String value1, String value2) {
            addCriterion("generationFee not between", value1, value2, "generationfee");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentIsNull() {
            addCriterion("generationFeeRepayment is null");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentIsNotNull() {
            addCriterion("generationFeeRepayment is not null");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentEqualTo(String value) {
            addCriterion("generationFeeRepayment =", value, "generationfeerepayment");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentNotEqualTo(String value) {
            addCriterion("generationFeeRepayment <>", value, "generationfeerepayment");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentGreaterThan(String value) {
            addCriterion("generationFeeRepayment >", value, "generationfeerepayment");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentGreaterThanOrEqualTo(String value) {
            addCriterion("generationFeeRepayment >=", value, "generationfeerepayment");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentLessThan(String value) {
            addCriterion("generationFeeRepayment <", value, "generationfeerepayment");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentLessThanOrEqualTo(String value) {
            addCriterion("generationFeeRepayment <=", value, "generationfeerepayment");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentLike(String value) {
            addCriterion("generationFeeRepayment like", value, "generationfeerepayment");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentNotLike(String value) {
            addCriterion("generationFeeRepayment not like", value, "generationfeerepayment");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentIn(List<String> values) {
            addCriterion("generationFeeRepayment in", values, "generationfeerepayment");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentNotIn(List<String> values) {
            addCriterion("generationFeeRepayment not in", values, "generationfeerepayment");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentBetween(String value1, String value2) {
            addCriterion("generationFeeRepayment between", value1, value2, "generationfeerepayment");
            return (Criteria) this;
        }

        public Criteria andGenerationfeerepaymentNotBetween(String value1, String value2) {
            addCriterion("generationFeeRepayment not between", value1, value2, "generationfeerepayment");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andAgentstatusIsNull() {
            addCriterion("agentStatus is null");
            return (Criteria) this;
        }

        public Criteria andAgentstatusIsNotNull() {
            addCriterion("agentStatus is not null");
            return (Criteria) this;
        }

        public Criteria andAgentstatusEqualTo(String value) {
            addCriterion("agentStatus =", value, "agentstatus");
            return (Criteria) this;
        }

        public Criteria andAgentstatusNotEqualTo(String value) {
            addCriterion("agentStatus <>", value, "agentstatus");
            return (Criteria) this;
        }

        public Criteria andAgentstatusGreaterThan(String value) {
            addCriterion("agentStatus >", value, "agentstatus");
            return (Criteria) this;
        }

        public Criteria andAgentstatusGreaterThanOrEqualTo(String value) {
            addCriterion("agentStatus >=", value, "agentstatus");
            return (Criteria) this;
        }

        public Criteria andAgentstatusLessThan(String value) {
            addCriterion("agentStatus <", value, "agentstatus");
            return (Criteria) this;
        }

        public Criteria andAgentstatusLessThanOrEqualTo(String value) {
            addCriterion("agentStatus <=", value, "agentstatus");
            return (Criteria) this;
        }

        public Criteria andAgentstatusLike(String value) {
            addCriterion("agentStatus like", value, "agentstatus");
            return (Criteria) this;
        }

        public Criteria andAgentstatusNotLike(String value) {
            addCriterion("agentStatus not like", value, "agentstatus");
            return (Criteria) this;
        }

        public Criteria andAgentstatusIn(List<String> values) {
            addCriterion("agentStatus in", values, "agentstatus");
            return (Criteria) this;
        }

        public Criteria andAgentstatusNotIn(List<String> values) {
            addCriterion("agentStatus not in", values, "agentstatus");
            return (Criteria) this;
        }

        public Criteria andAgentstatusBetween(String value1, String value2) {
            addCriterion("agentStatus between", value1, value2, "agentstatus");
            return (Criteria) this;
        }

        public Criteria andAgentstatusNotBetween(String value1, String value2) {
            addCriterion("agentStatus not between", value1, value2, "agentstatus");
            return (Criteria) this;
        }

        public Criteria andAgentidIsNull() {
            addCriterion("agentId is null");
            return (Criteria) this;
        }

        public Criteria andAgentidIsNotNull() {
            addCriterion("agentId is not null");
            return (Criteria) this;
        }

        public Criteria andAgentidEqualTo(String value) {
            addCriterion("agentId =", value, "agentid");
            return (Criteria) this;
        }

        public Criteria andAgentidNotEqualTo(String value) {
            addCriterion("agentId <>", value, "agentid");
            return (Criteria) this;
        }

        public Criteria andAgentidGreaterThan(String value) {
            addCriterion("agentId >", value, "agentid");
            return (Criteria) this;
        }

        public Criteria andAgentidGreaterThanOrEqualTo(String value) {
            addCriterion("agentId >=", value, "agentid");
            return (Criteria) this;
        }

        public Criteria andAgentidLessThan(String value) {
            addCriterion("agentId <", value, "agentid");
            return (Criteria) this;
        }

        public Criteria andAgentidLessThanOrEqualTo(String value) {
            addCriterion("agentId <=", value, "agentid");
            return (Criteria) this;
        }

        public Criteria andAgentidLike(String value) {
            addCriterion("agentId like", value, "agentid");
            return (Criteria) this;
        }

        public Criteria andAgentidNotLike(String value) {
            addCriterion("agentId not like", value, "agentid");
            return (Criteria) this;
        }

        public Criteria andAgentidIn(List<String> values) {
            addCriterion("agentId in", values, "agentid");
            return (Criteria) this;
        }

        public Criteria andAgentidNotIn(List<String> values) {
            addCriterion("agentId not in", values, "agentid");
            return (Criteria) this;
        }

        public Criteria andAgentidBetween(String value1, String value2) {
            addCriterion("agentId between", value1, value2, "agentid");
            return (Criteria) this;
        }

        public Criteria andAgentidNotBetween(String value1, String value2) {
            addCriterion("agentId not between", value1, value2, "agentid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidIsNull() {
            addCriterion("institutionId is null");
            return (Criteria) this;
        }

        public Criteria andInstitutionidIsNotNull() {
            addCriterion("institutionId is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutionidEqualTo(String value) {
            addCriterion("institutionId =", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidNotEqualTo(String value) {
            addCriterion("institutionId <>", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidGreaterThan(String value) {
            addCriterion("institutionId >", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidGreaterThanOrEqualTo(String value) {
            addCriterion("institutionId >=", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidLessThan(String value) {
            addCriterion("institutionId <", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidLessThanOrEqualTo(String value) {
            addCriterion("institutionId <=", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidLike(String value) {
            addCriterion("institutionId like", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidNotLike(String value) {
            addCriterion("institutionId not like", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidIn(List<String> values) {
            addCriterion("institutionId in", values, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidNotIn(List<String> values) {
            addCriterion("institutionId not in", values, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidBetween(String value1, String value2) {
            addCriterion("institutionId between", value1, value2, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidNotBetween(String value1, String value2) {
            addCriterion("institutionId not between", value1, value2, "institutionid");
            return (Criteria) this;
        }

        public Criteria andMertypeIsNull() {
            addCriterion("merType is null");
            return (Criteria) this;
        }

        public Criteria andMertypeIsNotNull() {
            addCriterion("merType is not null");
            return (Criteria) this;
        }

        public Criteria andMertypeEqualTo(String value) {
            addCriterion("merType =", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeNotEqualTo(String value) {
            addCriterion("merType <>", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeGreaterThan(String value) {
            addCriterion("merType >", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeGreaterThanOrEqualTo(String value) {
            addCriterion("merType >=", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeLessThan(String value) {
            addCriterion("merType <", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeLessThanOrEqualTo(String value) {
            addCriterion("merType <=", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeLike(String value) {
            addCriterion("merType like", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeNotLike(String value) {
            addCriterion("merType not like", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeIn(List<String> values) {
            addCriterion("merType in", values, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeNotIn(List<String> values) {
            addCriterion("merType not in", values, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeBetween(String value1, String value2) {
            addCriterion("merType between", value1, value2, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeNotBetween(String value1, String value2) {
            addCriterion("merType not between", value1, value2, "mertype");
            return (Criteria) this;
        }

        public Criteria andOnemeridIsNull() {
            addCriterion("oneMerId is null");
            return (Criteria) this;
        }

        public Criteria andOnemeridIsNotNull() {
            addCriterion("oneMerId is not null");
            return (Criteria) this;
        }

        public Criteria andOnemeridEqualTo(String value) {
            addCriterion("oneMerId =", value, "onemerid");
            return (Criteria) this;
        }

        public Criteria andOnemeridNotEqualTo(String value) {
            addCriterion("oneMerId <>", value, "onemerid");
            return (Criteria) this;
        }

        public Criteria andOnemeridGreaterThan(String value) {
            addCriterion("oneMerId >", value, "onemerid");
            return (Criteria) this;
        }

        public Criteria andOnemeridGreaterThanOrEqualTo(String value) {
            addCriterion("oneMerId >=", value, "onemerid");
            return (Criteria) this;
        }

        public Criteria andOnemeridLessThan(String value) {
            addCriterion("oneMerId <", value, "onemerid");
            return (Criteria) this;
        }

        public Criteria andOnemeridLessThanOrEqualTo(String value) {
            addCriterion("oneMerId <=", value, "onemerid");
            return (Criteria) this;
        }

        public Criteria andOnemeridLike(String value) {
            addCriterion("oneMerId like", value, "onemerid");
            return (Criteria) this;
        }

        public Criteria andOnemeridNotLike(String value) {
            addCriterion("oneMerId not like", value, "onemerid");
            return (Criteria) this;
        }

        public Criteria andOnemeridIn(List<String> values) {
            addCriterion("oneMerId in", values, "onemerid");
            return (Criteria) this;
        }

        public Criteria andOnemeridNotIn(List<String> values) {
            addCriterion("oneMerId not in", values, "onemerid");
            return (Criteria) this;
        }

        public Criteria andOnemeridBetween(String value1, String value2) {
            addCriterion("oneMerId between", value1, value2, "onemerid");
            return (Criteria) this;
        }

        public Criteria andOnemeridNotBetween(String value1, String value2) {
            addCriterion("oneMerId not between", value1, value2, "onemerid");
            return (Criteria) this;
        }

        public Criteria andTwomeridIsNull() {
            addCriterion("twoMerId is null");
            return (Criteria) this;
        }

        public Criteria andTwomeridIsNotNull() {
            addCriterion("twoMerId is not null");
            return (Criteria) this;
        }

        public Criteria andTwomeridEqualTo(String value) {
            addCriterion("twoMerId =", value, "twomerid");
            return (Criteria) this;
        }

        public Criteria andTwomeridNotEqualTo(String value) {
            addCriterion("twoMerId <>", value, "twomerid");
            return (Criteria) this;
        }

        public Criteria andTwomeridGreaterThan(String value) {
            addCriterion("twoMerId >", value, "twomerid");
            return (Criteria) this;
        }

        public Criteria andTwomeridGreaterThanOrEqualTo(String value) {
            addCriterion("twoMerId >=", value, "twomerid");
            return (Criteria) this;
        }

        public Criteria andTwomeridLessThan(String value) {
            addCriterion("twoMerId <", value, "twomerid");
            return (Criteria) this;
        }

        public Criteria andTwomeridLessThanOrEqualTo(String value) {
            addCriterion("twoMerId <=", value, "twomerid");
            return (Criteria) this;
        }

        public Criteria andTwomeridLike(String value) {
            addCriterion("twoMerId like", value, "twomerid");
            return (Criteria) this;
        }

        public Criteria andTwomeridNotLike(String value) {
            addCriterion("twoMerId not like", value, "twomerid");
            return (Criteria) this;
        }

        public Criteria andTwomeridIn(List<String> values) {
            addCriterion("twoMerId in", values, "twomerid");
            return (Criteria) this;
        }

        public Criteria andTwomeridNotIn(List<String> values) {
            addCriterion("twoMerId not in", values, "twomerid");
            return (Criteria) this;
        }

        public Criteria andTwomeridBetween(String value1, String value2) {
            addCriterion("twoMerId between", value1, value2, "twomerid");
            return (Criteria) this;
        }

        public Criteria andTwomeridNotBetween(String value1, String value2) {
            addCriterion("twoMerId not between", value1, value2, "twomerid");
            return (Criteria) this;
        }

        public Criteria andThreemeridIsNull() {
            addCriterion("threeMerId is null");
            return (Criteria) this;
        }

        public Criteria andThreemeridIsNotNull() {
            addCriterion("threeMerId is not null");
            return (Criteria) this;
        }

        public Criteria andThreemeridEqualTo(String value) {
            addCriterion("threeMerId =", value, "threemerid");
            return (Criteria) this;
        }

        public Criteria andThreemeridNotEqualTo(String value) {
            addCriterion("threeMerId <>", value, "threemerid");
            return (Criteria) this;
        }

        public Criteria andThreemeridGreaterThan(String value) {
            addCriterion("threeMerId >", value, "threemerid");
            return (Criteria) this;
        }

        public Criteria andThreemeridGreaterThanOrEqualTo(String value) {
            addCriterion("threeMerId >=", value, "threemerid");
            return (Criteria) this;
        }

        public Criteria andThreemeridLessThan(String value) {
            addCriterion("threeMerId <", value, "threemerid");
            return (Criteria) this;
        }

        public Criteria andThreemeridLessThanOrEqualTo(String value) {
            addCriterion("threeMerId <=", value, "threemerid");
            return (Criteria) this;
        }

        public Criteria andThreemeridLike(String value) {
            addCriterion("threeMerId like", value, "threemerid");
            return (Criteria) this;
        }

        public Criteria andThreemeridNotLike(String value) {
            addCriterion("threeMerId not like", value, "threemerid");
            return (Criteria) this;
        }

        public Criteria andThreemeridIn(List<String> values) {
            addCriterion("threeMerId in", values, "threemerid");
            return (Criteria) this;
        }

        public Criteria andThreemeridNotIn(List<String> values) {
            addCriterion("threeMerId not in", values, "threemerid");
            return (Criteria) this;
        }

        public Criteria andThreemeridBetween(String value1, String value2) {
            addCriterion("threeMerId between", value1, value2, "threemerid");
            return (Criteria) this;
        }

        public Criteria andThreemeridNotBetween(String value1, String value2) {
            addCriterion("threeMerId not between", value1, value2, "threemerid");
            return (Criteria) this;
        }

        public Criteria andFrozenIsNull() {
            addCriterion("frozen is null");
            return (Criteria) this;
        }

        public Criteria andFrozenIsNotNull() {
            addCriterion("frozen is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenEqualTo(String value) {
            addCriterion("frozen =", value, "frozen");
            return (Criteria) this;
        }

        public Criteria andFrozenNotEqualTo(String value) {
            addCriterion("frozen <>", value, "frozen");
            return (Criteria) this;
        }

        public Criteria andFrozenGreaterThan(String value) {
            addCriterion("frozen >", value, "frozen");
            return (Criteria) this;
        }

        public Criteria andFrozenGreaterThanOrEqualTo(String value) {
            addCriterion("frozen >=", value, "frozen");
            return (Criteria) this;
        }

        public Criteria andFrozenLessThan(String value) {
            addCriterion("frozen <", value, "frozen");
            return (Criteria) this;
        }

        public Criteria andFrozenLessThanOrEqualTo(String value) {
            addCriterion("frozen <=", value, "frozen");
            return (Criteria) this;
        }

        public Criteria andFrozenLike(String value) {
            addCriterion("frozen like", value, "frozen");
            return (Criteria) this;
        }

        public Criteria andFrozenNotLike(String value) {
            addCriterion("frozen not like", value, "frozen");
            return (Criteria) this;
        }

        public Criteria andFrozenIn(List<String> values) {
            addCriterion("frozen in", values, "frozen");
            return (Criteria) this;
        }

        public Criteria andFrozenNotIn(List<String> values) {
            addCriterion("frozen not in", values, "frozen");
            return (Criteria) this;
        }

        public Criteria andFrozenBetween(String value1, String value2) {
            addCriterion("frozen between", value1, value2, "frozen");
            return (Criteria) this;
        }

        public Criteria andFrozenNotBetween(String value1, String value2) {
            addCriterion("frozen not between", value1, value2, "frozen");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlIsNull() {
            addCriterion("faceImgUrl is null");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlIsNotNull() {
            addCriterion("faceImgUrl is not null");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlEqualTo(String value) {
            addCriterion("faceImgUrl =", value, "faceimgurl");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlNotEqualTo(String value) {
            addCriterion("faceImgUrl <>", value, "faceimgurl");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlGreaterThan(String value) {
            addCriterion("faceImgUrl >", value, "faceimgurl");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlGreaterThanOrEqualTo(String value) {
            addCriterion("faceImgUrl >=", value, "faceimgurl");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlLessThan(String value) {
            addCriterion("faceImgUrl <", value, "faceimgurl");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlLessThanOrEqualTo(String value) {
            addCriterion("faceImgUrl <=", value, "faceimgurl");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlLike(String value) {
            addCriterion("faceImgUrl like", value, "faceimgurl");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlNotLike(String value) {
            addCriterion("faceImgUrl not like", value, "faceimgurl");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlIn(List<String> values) {
            addCriterion("faceImgUrl in", values, "faceimgurl");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlNotIn(List<String> values) {
            addCriterion("faceImgUrl not in", values, "faceimgurl");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlBetween(String value1, String value2) {
            addCriterion("faceImgUrl between", value1, value2, "faceimgurl");
            return (Criteria) this;
        }

        public Criteria andFaceimgurlNotBetween(String value1, String value2) {
            addCriterion("faceImgUrl not between", value1, value2, "faceimgurl");
            return (Criteria) this;
        }

        public Criteria andRegdateIsNull() {
            addCriterion("regDate is null");
            return (Criteria) this;
        }

        public Criteria andRegdateIsNotNull() {
            addCriterion("regDate is not null");
            return (Criteria) this;
        }

        public Criteria andRegdateEqualTo(String value) {
            addCriterion("regDate =", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateNotEqualTo(String value) {
            addCriterion("regDate <>", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateGreaterThan(String value) {
            addCriterion("regDate >", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateGreaterThanOrEqualTo(String value) {
            addCriterion("regDate >=", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateLessThan(String value) {
            addCriterion("regDate <", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateLessThanOrEqualTo(String value) {
            addCriterion("regDate <=", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateLike(String value) {
            addCriterion("regDate like", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateNotLike(String value) {
            addCriterion("regDate not like", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateIn(List<String> values) {
            addCriterion("regDate in", values, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateNotIn(List<String> values) {
            addCriterion("regDate not in", values, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateBetween(String value1, String value2) {
            addCriterion("regDate between", value1, value2, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateNotBetween(String value1, String value2) {
            addCriterion("regDate not between", value1, value2, "regdate");
            return (Criteria) this;
        }

        public Criteria andMerstattimeIsNull() {
            addCriterion("merStatTime is null");
            return (Criteria) this;
        }

        public Criteria andMerstattimeIsNotNull() {
            addCriterion("merStatTime is not null");
            return (Criteria) this;
        }

        public Criteria andMerstattimeEqualTo(String value) {
            addCriterion("merStatTime =", value, "merstattime");
            return (Criteria) this;
        }

        public Criteria andMerstattimeNotEqualTo(String value) {
            addCriterion("merStatTime <>", value, "merstattime");
            return (Criteria) this;
        }

        public Criteria andMerstattimeGreaterThan(String value) {
            addCriterion("merStatTime >", value, "merstattime");
            return (Criteria) this;
        }

        public Criteria andMerstattimeGreaterThanOrEqualTo(String value) {
            addCriterion("merStatTime >=", value, "merstattime");
            return (Criteria) this;
        }

        public Criteria andMerstattimeLessThan(String value) {
            addCriterion("merStatTime <", value, "merstattime");
            return (Criteria) this;
        }

        public Criteria andMerstattimeLessThanOrEqualTo(String value) {
            addCriterion("merStatTime <=", value, "merstattime");
            return (Criteria) this;
        }

        public Criteria andMerstattimeLike(String value) {
            addCriterion("merStatTime like", value, "merstattime");
            return (Criteria) this;
        }

        public Criteria andMerstattimeNotLike(String value) {
            addCriterion("merStatTime not like", value, "merstattime");
            return (Criteria) this;
        }

        public Criteria andMerstattimeIn(List<String> values) {
            addCriterion("merStatTime in", values, "merstattime");
            return (Criteria) this;
        }

        public Criteria andMerstattimeNotIn(List<String> values) {
            addCriterion("merStatTime not in", values, "merstattime");
            return (Criteria) this;
        }

        public Criteria andMerstattimeBetween(String value1, String value2) {
            addCriterion("merStatTime between", value1, value2, "merstattime");
            return (Criteria) this;
        }

        public Criteria andMerstattimeNotBetween(String value1, String value2) {
            addCriterion("merStatTime not between", value1, value2, "merstattime");
            return (Criteria) this;
        }

        public Criteria andStatusdateIsNull() {
            addCriterion("statusDate is null");
            return (Criteria) this;
        }

        public Criteria andStatusdateIsNotNull() {
            addCriterion("statusDate is not null");
            return (Criteria) this;
        }

        public Criteria andStatusdateEqualTo(String value) {
            addCriterion("statusDate =", value, "statusdate");
            return (Criteria) this;
        }

        public Criteria andStatusdateNotEqualTo(String value) {
            addCriterion("statusDate <>", value, "statusdate");
            return (Criteria) this;
        }

        public Criteria andStatusdateGreaterThan(String value) {
            addCriterion("statusDate >", value, "statusdate");
            return (Criteria) this;
        }

        public Criteria andStatusdateGreaterThanOrEqualTo(String value) {
            addCriterion("statusDate >=", value, "statusdate");
            return (Criteria) this;
        }

        public Criteria andStatusdateLessThan(String value) {
            addCriterion("statusDate <", value, "statusdate");
            return (Criteria) this;
        }

        public Criteria andStatusdateLessThanOrEqualTo(String value) {
            addCriterion("statusDate <=", value, "statusdate");
            return (Criteria) this;
        }

        public Criteria andStatusdateLike(String value) {
            addCriterion("statusDate like", value, "statusdate");
            return (Criteria) this;
        }

        public Criteria andStatusdateNotLike(String value) {
            addCriterion("statusDate not like", value, "statusdate");
            return (Criteria) this;
        }

        public Criteria andStatusdateIn(List<String> values) {
            addCriterion("statusDate in", values, "statusdate");
            return (Criteria) this;
        }

        public Criteria andStatusdateNotIn(List<String> values) {
            addCriterion("statusDate not in", values, "statusdate");
            return (Criteria) this;
        }

        public Criteria andStatusdateBetween(String value1, String value2) {
            addCriterion("statusDate between", value1, value2, "statusdate");
            return (Criteria) this;
        }

        public Criteria andStatusdateNotBetween(String value1, String value2) {
            addCriterion("statusDate not between", value1, value2, "statusdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("startDate is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("startDate is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(String value) {
            addCriterion("startDate =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(String value) {
            addCriterion("startDate <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(String value) {
            addCriterion("startDate >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(String value) {
            addCriterion("startDate >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(String value) {
            addCriterion("startDate <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(String value) {
            addCriterion("startDate <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLike(String value) {
            addCriterion("startDate like", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotLike(String value) {
            addCriterion("startDate not like", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<String> values) {
            addCriterion("startDate in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<String> values) {
            addCriterion("startDate not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(String value1, String value2) {
            addCriterion("startDate between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(String value1, String value2) {
            addCriterion("startDate not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andFinishdateIsNull() {
            addCriterion("finishDate is null");
            return (Criteria) this;
        }

        public Criteria andFinishdateIsNotNull() {
            addCriterion("finishDate is not null");
            return (Criteria) this;
        }

        public Criteria andFinishdateEqualTo(String value) {
            addCriterion("finishDate =", value, "finishdate");
            return (Criteria) this;
        }

        public Criteria andFinishdateNotEqualTo(String value) {
            addCriterion("finishDate <>", value, "finishdate");
            return (Criteria) this;
        }

        public Criteria andFinishdateGreaterThan(String value) {
            addCriterion("finishDate >", value, "finishdate");
            return (Criteria) this;
        }

        public Criteria andFinishdateGreaterThanOrEqualTo(String value) {
            addCriterion("finishDate >=", value, "finishdate");
            return (Criteria) this;
        }

        public Criteria andFinishdateLessThan(String value) {
            addCriterion("finishDate <", value, "finishdate");
            return (Criteria) this;
        }

        public Criteria andFinishdateLessThanOrEqualTo(String value) {
            addCriterion("finishDate <=", value, "finishdate");
            return (Criteria) this;
        }

        public Criteria andFinishdateLike(String value) {
            addCriterion("finishDate like", value, "finishdate");
            return (Criteria) this;
        }

        public Criteria andFinishdateNotLike(String value) {
            addCriterion("finishDate not like", value, "finishdate");
            return (Criteria) this;
        }

        public Criteria andFinishdateIn(List<String> values) {
            addCriterion("finishDate in", values, "finishdate");
            return (Criteria) this;
        }

        public Criteria andFinishdateNotIn(List<String> values) {
            addCriterion("finishDate not in", values, "finishdate");
            return (Criteria) this;
        }

        public Criteria andFinishdateBetween(String value1, String value2) {
            addCriterion("finishDate between", value1, value2, "finishdate");
            return (Criteria) this;
        }

        public Criteria andFinishdateNotBetween(String value1, String value2) {
            addCriterion("finishDate not between", value1, value2, "finishdate");
            return (Criteria) this;
        }

        public Criteria andAppidIsNull() {
            addCriterion("appId is null");
            return (Criteria) this;
        }

        public Criteria andAppidIsNotNull() {
            addCriterion("appId is not null");
            return (Criteria) this;
        }

        public Criteria andAppidEqualTo(String value) {
            addCriterion("appId =", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotEqualTo(String value) {
            addCriterion("appId <>", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThan(String value) {
            addCriterion("appId >", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThanOrEqualTo(String value) {
            addCriterion("appId >=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThan(String value) {
            addCriterion("appId <", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThanOrEqualTo(String value) {
            addCriterion("appId <=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLike(String value) {
            addCriterion("appId like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotLike(String value) {
            addCriterion("appId not like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidIn(List<String> values) {
            addCriterion("appId in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotIn(List<String> values) {
            addCriterion("appId not in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidBetween(String value1, String value2) {
            addCriterion("appId between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotBetween(String value1, String value2) {
            addCriterion("appId not between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andAppnameIsNull() {
            addCriterion("appName is null");
            return (Criteria) this;
        }

        public Criteria andAppnameIsNotNull() {
            addCriterion("appName is not null");
            return (Criteria) this;
        }

        public Criteria andAppnameEqualTo(String value) {
            addCriterion("appName =", value, "appname");
            return (Criteria) this;
        }

        public Criteria andAppnameNotEqualTo(String value) {
            addCriterion("appName <>", value, "appname");
            return (Criteria) this;
        }

        public Criteria andAppnameGreaterThan(String value) {
            addCriterion("appName >", value, "appname");
            return (Criteria) this;
        }

        public Criteria andAppnameGreaterThanOrEqualTo(String value) {
            addCriterion("appName >=", value, "appname");
            return (Criteria) this;
        }

        public Criteria andAppnameLessThan(String value) {
            addCriterion("appName <", value, "appname");
            return (Criteria) this;
        }

        public Criteria andAppnameLessThanOrEqualTo(String value) {
            addCriterion("appName <=", value, "appname");
            return (Criteria) this;
        }

        public Criteria andAppnameLike(String value) {
            addCriterion("appName like", value, "appname");
            return (Criteria) this;
        }

        public Criteria andAppnameNotLike(String value) {
            addCriterion("appName not like", value, "appname");
            return (Criteria) this;
        }

        public Criteria andAppnameIn(List<String> values) {
            addCriterion("appName in", values, "appname");
            return (Criteria) this;
        }

        public Criteria andAppnameNotIn(List<String> values) {
            addCriterion("appName not in", values, "appname");
            return (Criteria) this;
        }

        public Criteria andAppnameBetween(String value1, String value2) {
            addCriterion("appName between", value1, value2, "appname");
            return (Criteria) this;
        }

        public Criteria andAppnameNotBetween(String value1, String value2) {
            addCriterion("appName not between", value1, value2, "appname");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNull() {
            addCriterion("balance is null");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNotNull() {
            addCriterion("balance is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceEqualTo(BigDecimal value) {
            addCriterion("balance =", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotEqualTo(BigDecimal value) {
            addCriterion("balance <>", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThan(BigDecimal value) {
            addCriterion("balance >", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("balance >=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThan(BigDecimal value) {
            addCriterion("balance <", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("balance <=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceIn(List<BigDecimal> values) {
            addCriterion("balance in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotIn(List<BigDecimal> values) {
            addCriterion("balance not in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balance between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balance not between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitIsNull() {
            addCriterion("balanceProfit is null");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitIsNotNull() {
            addCriterion("balanceProfit is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitEqualTo(BigDecimal value) {
            addCriterion("balanceProfit =", value, "balanceprofit");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitNotEqualTo(BigDecimal value) {
            addCriterion("balanceProfit <>", value, "balanceprofit");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitGreaterThan(BigDecimal value) {
            addCriterion("balanceProfit >", value, "balanceprofit");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("balanceProfit >=", value, "balanceprofit");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitLessThan(BigDecimal value) {
            addCriterion("balanceProfit <", value, "balanceprofit");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("balanceProfit <=", value, "balanceprofit");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitIn(List<BigDecimal> values) {
            addCriterion("balanceProfit in", values, "balanceprofit");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitNotIn(List<BigDecimal> values) {
            addCriterion("balanceProfit not in", values, "balanceprofit");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balanceProfit between", value1, value2, "balanceprofit");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balanceProfit not between", value1, value2, "balanceprofit");
            return (Criteria) this;
        }

        public Criteria andBalancefrozenIsNull() {
            addCriterion("balanceFrozen is null");
            return (Criteria) this;
        }

        public Criteria andBalancefrozenIsNotNull() {
            addCriterion("balanceFrozen is not null");
            return (Criteria) this;
        }

        public Criteria andBalancefrozenEqualTo(BigDecimal value) {
            addCriterion("balanceFrozen =", value, "balancefrozen");
            return (Criteria) this;
        }

        public Criteria andBalancefrozenNotEqualTo(BigDecimal value) {
            addCriterion("balanceFrozen <>", value, "balancefrozen");
            return (Criteria) this;
        }

        public Criteria andBalancefrozenGreaterThan(BigDecimal value) {
            addCriterion("balanceFrozen >", value, "balancefrozen");
            return (Criteria) this;
        }

        public Criteria andBalancefrozenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("balanceFrozen >=", value, "balancefrozen");
            return (Criteria) this;
        }

        public Criteria andBalancefrozenLessThan(BigDecimal value) {
            addCriterion("balanceFrozen <", value, "balancefrozen");
            return (Criteria) this;
        }

        public Criteria andBalancefrozenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("balanceFrozen <=", value, "balancefrozen");
            return (Criteria) this;
        }

        public Criteria andBalancefrozenIn(List<BigDecimal> values) {
            addCriterion("balanceFrozen in", values, "balancefrozen");
            return (Criteria) this;
        }

        public Criteria andBalancefrozenNotIn(List<BigDecimal> values) {
            addCriterion("balanceFrozen not in", values, "balancefrozen");
            return (Criteria) this;
        }

        public Criteria andBalancefrozenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balanceFrozen between", value1, value2, "balancefrozen");
            return (Criteria) this;
        }

        public Criteria andBalancefrozenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balanceFrozen not between", value1, value2, "balancefrozen");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitfrozenIsNull() {
            addCriterion("balanceProfitFrozen is null");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitfrozenIsNotNull() {
            addCriterion("balanceProfitFrozen is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitfrozenEqualTo(BigDecimal value) {
            addCriterion("balanceProfitFrozen =", value, "balanceprofitfrozen");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitfrozenNotEqualTo(BigDecimal value) {
            addCriterion("balanceProfitFrozen <>", value, "balanceprofitfrozen");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitfrozenGreaterThan(BigDecimal value) {
            addCriterion("balanceProfitFrozen >", value, "balanceprofitfrozen");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitfrozenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("balanceProfitFrozen >=", value, "balanceprofitfrozen");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitfrozenLessThan(BigDecimal value) {
            addCriterion("balanceProfitFrozen <", value, "balanceprofitfrozen");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitfrozenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("balanceProfitFrozen <=", value, "balanceprofitfrozen");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitfrozenIn(List<BigDecimal> values) {
            addCriterion("balanceProfitFrozen in", values, "balanceprofitfrozen");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitfrozenNotIn(List<BigDecimal> values) {
            addCriterion("balanceProfitFrozen not in", values, "balanceprofitfrozen");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitfrozenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balanceProfitFrozen between", value1, value2, "balanceprofitfrozen");
            return (Criteria) this;
        }

        public Criteria andBalanceprofitfrozenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balanceProfitFrozen not between", value1, value2, "balanceprofitfrozen");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andUsedIsNull() {
            addCriterion("used is null");
            return (Criteria) this;
        }

        public Criteria andUsedIsNotNull() {
            addCriterion("used is not null");
            return (Criteria) this;
        }

        public Criteria andUsedEqualTo(String value) {
            addCriterion("used =", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedNotEqualTo(String value) {
            addCriterion("used <>", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedGreaterThan(String value) {
            addCriterion("used >", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedGreaterThanOrEqualTo(String value) {
            addCriterion("used >=", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedLessThan(String value) {
            addCriterion("used <", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedLessThanOrEqualTo(String value) {
            addCriterion("used <=", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedLike(String value) {
            addCriterion("used like", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedNotLike(String value) {
            addCriterion("used not like", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedIn(List<String> values) {
            addCriterion("used in", values, "used");
            return (Criteria) this;
        }

        public Criteria andUsedNotIn(List<String> values) {
            addCriterion("used not in", values, "used");
            return (Criteria) this;
        }

        public Criteria andUsedBetween(String value1, String value2) {
            addCriterion("used between", value1, value2, "used");
            return (Criteria) this;
        }

        public Criteria andUsedNotBetween(String value1, String value2) {
            addCriterion("used not between", value1, value2, "used");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mp_merchants
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mp_merchants
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}