package com.battcn.entity;

public class Num {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.merType
     *
     * @mbggenerated
     */
    private String mertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.num
     *
     * @mbggenerated
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.validTime
     *
     * @mbggenerated
     */
    private String validtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.oneMerchant
     *
     * @mbggenerated
     */
    private Long onemerchant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.twoMerchant
     *
     * @mbggenerated
     */
    private Long twomerchant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.ThreeMerchant
     *
     * @mbggenerated
     */
    private Long threemerchant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.oneAgent
     *
     * @mbggenerated
     */
    private Long oneagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.twoAgent
     *
     * @mbggenerated
     */
    private Long twoagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.countyAgent
     *
     * @mbggenerated
     */
    private Long countyagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.cityAgent
     *
     * @mbggenerated
     */
    private Long cityagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.provinceAgent
     *
     * @mbggenerated
     */
    private Long provinceagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.institution
     *
     * @mbggenerated
     */
    private Long institution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.amount
     *
     * @mbggenerated
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.payType
     *
     * @mbggenerated
     */
    private String paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.vipType
     *
     * @mbggenerated
     */
    private String viptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.topAgent
     *
     * @mbggenerated
     */
    private String topagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_num.levelWeight
     *
     * @mbggenerated
     */
    private Long levelweight;
    
    private String mertypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.id
     *
     * @return the value of t_mp_num.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.id
     *
     * @param id the value for t_mp_num.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.merType
     *
     * @return the value of t_mp_num.merType
     *
     * @mbggenerated
     */
    public String getMertype() {
        return mertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.merType
     *
     * @param mertype the value for t_mp_num.merType
     *
     * @mbggenerated
     */
    public void setMertype(String mertype) {
        this.mertype = mertype == null ? null : mertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.num
     *
     * @return the value of t_mp_num.num
     *
     * @mbggenerated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.num
     *
     * @param num the value for t_mp_num.num
     *
     * @mbggenerated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.validTime
     *
     * @return the value of t_mp_num.validTime
     *
     * @mbggenerated
     */
    public String getValidtime() {
        return validtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.validTime
     *
     * @param validtime the value for t_mp_num.validTime
     *
     * @mbggenerated
     */
    public void setValidtime(String validtime) {
        this.validtime = validtime == null ? null : validtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.oneMerchant
     *
     * @return the value of t_mp_num.oneMerchant
     *
     * @mbggenerated
     */
    public Long getOnemerchant() {
        return onemerchant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.oneMerchant
     *
     * @param onemerchant the value for t_mp_num.oneMerchant
     *
     * @mbggenerated
     */
    public void setOnemerchant(Long onemerchant) {
        this.onemerchant = onemerchant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.twoMerchant
     *
     * @return the value of t_mp_num.twoMerchant
     *
     * @mbggenerated
     */
    public Long getTwomerchant() {
        return twomerchant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.twoMerchant
     *
     * @param twomerchant the value for t_mp_num.twoMerchant
     *
     * @mbggenerated
     */
    public void setTwomerchant(Long twomerchant) {
        this.twomerchant = twomerchant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.ThreeMerchant
     *
     * @return the value of t_mp_num.ThreeMerchant
     *
     * @mbggenerated
     */
    public Long getThreemerchant() {
        return threemerchant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.ThreeMerchant
     *
     * @param threemerchant the value for t_mp_num.ThreeMerchant
     *
     * @mbggenerated
     */
    public void setThreemerchant(Long threemerchant) {
        this.threemerchant = threemerchant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.oneAgent
     *
     * @return the value of t_mp_num.oneAgent
     *
     * @mbggenerated
     */
    public Long getOneagent() {
        return oneagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.oneAgent
     *
     * @param oneagent the value for t_mp_num.oneAgent
     *
     * @mbggenerated
     */
    public void setOneagent(Long oneagent) {
        this.oneagent = oneagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.twoAgent
     *
     * @return the value of t_mp_num.twoAgent
     *
     * @mbggenerated
     */
    public Long getTwoagent() {
        return twoagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.twoAgent
     *
     * @param twoagent the value for t_mp_num.twoAgent
     *
     * @mbggenerated
     */
    public void setTwoagent(Long twoagent) {
        this.twoagent = twoagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.countyAgent
     *
     * @return the value of t_mp_num.countyAgent
     *
     * @mbggenerated
     */
    public Long getCountyagent() {
        return countyagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.countyAgent
     *
     * @param countyagent the value for t_mp_num.countyAgent
     *
     * @mbggenerated
     */
    public void setCountyagent(Long countyagent) {
        this.countyagent = countyagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.cityAgent
     *
     * @return the value of t_mp_num.cityAgent
     *
     * @mbggenerated
     */
    public Long getCityagent() {
        return cityagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.cityAgent
     *
     * @param cityagent the value for t_mp_num.cityAgent
     *
     * @mbggenerated
     */
    public void setCityagent(Long cityagent) {
        this.cityagent = cityagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.provinceAgent
     *
     * @return the value of t_mp_num.provinceAgent
     *
     * @mbggenerated
     */
    public Long getProvinceagent() {
        return provinceagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.provinceAgent
     *
     * @param provinceagent the value for t_mp_num.provinceAgent
     *
     * @mbggenerated
     */
    public void setProvinceagent(Long provinceagent) {
        this.provinceagent = provinceagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.institution
     *
     * @return the value of t_mp_num.institution
     *
     * @mbggenerated
     */
    public Long getInstitution() {
        return institution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.institution
     *
     * @param institution the value for t_mp_num.institution
     *
     * @mbggenerated
     */
    public void setInstitution(Long institution) {
        this.institution = institution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.amount
     *
     * @return the value of t_mp_num.amount
     *
     * @mbggenerated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.amount
     *
     * @param amount the value for t_mp_num.amount
     *
     * @mbggenerated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.level
     *
     * @return the value of t_mp_num.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.level
     *
     * @param level the value for t_mp_num.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.payType
     *
     * @return the value of t_mp_num.payType
     *
     * @mbggenerated
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.payType
     *
     * @param paytype the value for t_mp_num.payType
     *
     * @mbggenerated
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.vipType
     *
     * @return the value of t_mp_num.vipType
     *
     * @mbggenerated
     */
    public String getViptype() {
        return viptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.vipType
     *
     * @param viptype the value for t_mp_num.vipType
     *
     * @mbggenerated
     */
    public void setViptype(String viptype) {
        this.viptype = viptype == null ? null : viptype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.topAgent
     *
     * @return the value of t_mp_num.topAgent
     *
     * @mbggenerated
     */
    public String getTopagent() {
        return topagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.topAgent
     *
     * @param topagent the value for t_mp_num.topAgent
     *
     * @mbggenerated
     */
    public void setTopagent(String topagent) {
        this.topagent = topagent == null ? null : topagent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_num.levelWeight
     *
     * @return the value of t_mp_num.levelWeight
     *
     * @mbggenerated
     */
    public Long getLevelweight() {
        return levelweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_num.levelWeight
     *
     * @param levelweight the value for t_mp_num.levelWeight
     *
     * @mbggenerated
     */
    public void setLevelweight(Long levelweight) {
        this.levelweight = levelweight;
    }

	public String getMertypeName() {
		return mertypeName;
	}

	public void setMertypeName(String mertypeName) {
		this.mertypeName = mertypeName;
	}
    
}