package com.battcn.entity;

import java.util.ArrayList;
import java.util.List;

public class NumExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    public NumExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMertypeIsNull() {
            addCriterion("merType is null");
            return (Criteria) this;
        }

        public Criteria andMertypeIsNotNull() {
            addCriterion("merType is not null");
            return (Criteria) this;
        }

        public Criteria andMertypeEqualTo(String value) {
            addCriterion("merType =", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeNotEqualTo(String value) {
            addCriterion("merType <>", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeGreaterThan(String value) {
            addCriterion("merType >", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeGreaterThanOrEqualTo(String value) {
            addCriterion("merType >=", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeLessThan(String value) {
            addCriterion("merType <", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeLessThanOrEqualTo(String value) {
            addCriterion("merType <=", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeLike(String value) {
            addCriterion("merType like", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeNotLike(String value) {
            addCriterion("merType not like", value, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeIn(List<String> values) {
            addCriterion("merType in", values, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeNotIn(List<String> values) {
            addCriterion("merType not in", values, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeBetween(String value1, String value2) {
            addCriterion("merType between", value1, value2, "mertype");
            return (Criteria) this;
        }

        public Criteria andMertypeNotBetween(String value1, String value2) {
            addCriterion("merType not between", value1, value2, "mertype");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andValidtimeIsNull() {
            addCriterion("validTime is null");
            return (Criteria) this;
        }

        public Criteria andValidtimeIsNotNull() {
            addCriterion("validTime is not null");
            return (Criteria) this;
        }

        public Criteria andValidtimeEqualTo(String value) {
            addCriterion("validTime =", value, "validtime");
            return (Criteria) this;
        }

        public Criteria andValidtimeNotEqualTo(String value) {
            addCriterion("validTime <>", value, "validtime");
            return (Criteria) this;
        }

        public Criteria andValidtimeGreaterThan(String value) {
            addCriterion("validTime >", value, "validtime");
            return (Criteria) this;
        }

        public Criteria andValidtimeGreaterThanOrEqualTo(String value) {
            addCriterion("validTime >=", value, "validtime");
            return (Criteria) this;
        }

        public Criteria andValidtimeLessThan(String value) {
            addCriterion("validTime <", value, "validtime");
            return (Criteria) this;
        }

        public Criteria andValidtimeLessThanOrEqualTo(String value) {
            addCriterion("validTime <=", value, "validtime");
            return (Criteria) this;
        }

        public Criteria andValidtimeLike(String value) {
            addCriterion("validTime like", value, "validtime");
            return (Criteria) this;
        }

        public Criteria andValidtimeNotLike(String value) {
            addCriterion("validTime not like", value, "validtime");
            return (Criteria) this;
        }

        public Criteria andValidtimeIn(List<String> values) {
            addCriterion("validTime in", values, "validtime");
            return (Criteria) this;
        }

        public Criteria andValidtimeNotIn(List<String> values) {
            addCriterion("validTime not in", values, "validtime");
            return (Criteria) this;
        }

        public Criteria andValidtimeBetween(String value1, String value2) {
            addCriterion("validTime between", value1, value2, "validtime");
            return (Criteria) this;
        }

        public Criteria andValidtimeNotBetween(String value1, String value2) {
            addCriterion("validTime not between", value1, value2, "validtime");
            return (Criteria) this;
        }

        public Criteria andOnemerchantIsNull() {
            addCriterion("oneMerchant is null");
            return (Criteria) this;
        }

        public Criteria andOnemerchantIsNotNull() {
            addCriterion("oneMerchant is not null");
            return (Criteria) this;
        }

        public Criteria andOnemerchantEqualTo(Long value) {
            addCriterion("oneMerchant =", value, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantNotEqualTo(Long value) {
            addCriterion("oneMerchant <>", value, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantGreaterThan(Long value) {
            addCriterion("oneMerchant >", value, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantGreaterThanOrEqualTo(Long value) {
            addCriterion("oneMerchant >=", value, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantLessThan(Long value) {
            addCriterion("oneMerchant <", value, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantLessThanOrEqualTo(Long value) {
            addCriterion("oneMerchant <=", value, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantIn(List<Long> values) {
            addCriterion("oneMerchant in", values, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantNotIn(List<Long> values) {
            addCriterion("oneMerchant not in", values, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantBetween(Long value1, Long value2) {
            addCriterion("oneMerchant between", value1, value2, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantNotBetween(Long value1, Long value2) {
            addCriterion("oneMerchant not between", value1, value2, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantIsNull() {
            addCriterion("twoMerchant is null");
            return (Criteria) this;
        }

        public Criteria andTwomerchantIsNotNull() {
            addCriterion("twoMerchant is not null");
            return (Criteria) this;
        }

        public Criteria andTwomerchantEqualTo(Long value) {
            addCriterion("twoMerchant =", value, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantNotEqualTo(Long value) {
            addCriterion("twoMerchant <>", value, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantGreaterThan(Long value) {
            addCriterion("twoMerchant >", value, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantGreaterThanOrEqualTo(Long value) {
            addCriterion("twoMerchant >=", value, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantLessThan(Long value) {
            addCriterion("twoMerchant <", value, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantLessThanOrEqualTo(Long value) {
            addCriterion("twoMerchant <=", value, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantIn(List<Long> values) {
            addCriterion("twoMerchant in", values, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantNotIn(List<Long> values) {
            addCriterion("twoMerchant not in", values, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantBetween(Long value1, Long value2) {
            addCriterion("twoMerchant between", value1, value2, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantNotBetween(Long value1, Long value2) {
            addCriterion("twoMerchant not between", value1, value2, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andThreemerchantIsNull() {
            addCriterion("ThreeMerchant is null");
            return (Criteria) this;
        }

        public Criteria andThreemerchantIsNotNull() {
            addCriterion("ThreeMerchant is not null");
            return (Criteria) this;
        }

        public Criteria andThreemerchantEqualTo(Long value) {
            addCriterion("ThreeMerchant =", value, "threemerchant");
            return (Criteria) this;
        }

        public Criteria andThreemerchantNotEqualTo(Long value) {
            addCriterion("ThreeMerchant <>", value, "threemerchant");
            return (Criteria) this;
        }

        public Criteria andThreemerchantGreaterThan(Long value) {
            addCriterion("ThreeMerchant >", value, "threemerchant");
            return (Criteria) this;
        }

        public Criteria andThreemerchantGreaterThanOrEqualTo(Long value) {
            addCriterion("ThreeMerchant >=", value, "threemerchant");
            return (Criteria) this;
        }

        public Criteria andThreemerchantLessThan(Long value) {
            addCriterion("ThreeMerchant <", value, "threemerchant");
            return (Criteria) this;
        }

        public Criteria andThreemerchantLessThanOrEqualTo(Long value) {
            addCriterion("ThreeMerchant <=", value, "threemerchant");
            return (Criteria) this;
        }

        public Criteria andThreemerchantIn(List<Long> values) {
            addCriterion("ThreeMerchant in", values, "threemerchant");
            return (Criteria) this;
        }

        public Criteria andThreemerchantNotIn(List<Long> values) {
            addCriterion("ThreeMerchant not in", values, "threemerchant");
            return (Criteria) this;
        }

        public Criteria andThreemerchantBetween(Long value1, Long value2) {
            addCriterion("ThreeMerchant between", value1, value2, "threemerchant");
            return (Criteria) this;
        }

        public Criteria andThreemerchantNotBetween(Long value1, Long value2) {
            addCriterion("ThreeMerchant not between", value1, value2, "threemerchant");
            return (Criteria) this;
        }

        public Criteria andOneagentIsNull() {
            addCriterion("oneAgent is null");
            return (Criteria) this;
        }

        public Criteria andOneagentIsNotNull() {
            addCriterion("oneAgent is not null");
            return (Criteria) this;
        }

        public Criteria andOneagentEqualTo(Long value) {
            addCriterion("oneAgent =", value, "oneagent");
            return (Criteria) this;
        }

        public Criteria andOneagentNotEqualTo(Long value) {
            addCriterion("oneAgent <>", value, "oneagent");
            return (Criteria) this;
        }

        public Criteria andOneagentGreaterThan(Long value) {
            addCriterion("oneAgent >", value, "oneagent");
            return (Criteria) this;
        }

        public Criteria andOneagentGreaterThanOrEqualTo(Long value) {
            addCriterion("oneAgent >=", value, "oneagent");
            return (Criteria) this;
        }

        public Criteria andOneagentLessThan(Long value) {
            addCriterion("oneAgent <", value, "oneagent");
            return (Criteria) this;
        }

        public Criteria andOneagentLessThanOrEqualTo(Long value) {
            addCriterion("oneAgent <=", value, "oneagent");
            return (Criteria) this;
        }

        public Criteria andOneagentIn(List<Long> values) {
            addCriterion("oneAgent in", values, "oneagent");
            return (Criteria) this;
        }

        public Criteria andOneagentNotIn(List<Long> values) {
            addCriterion("oneAgent not in", values, "oneagent");
            return (Criteria) this;
        }

        public Criteria andOneagentBetween(Long value1, Long value2) {
            addCriterion("oneAgent between", value1, value2, "oneagent");
            return (Criteria) this;
        }

        public Criteria andOneagentNotBetween(Long value1, Long value2) {
            addCriterion("oneAgent not between", value1, value2, "oneagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentIsNull() {
            addCriterion("twoAgent is null");
            return (Criteria) this;
        }

        public Criteria andTwoagentIsNotNull() {
            addCriterion("twoAgent is not null");
            return (Criteria) this;
        }

        public Criteria andTwoagentEqualTo(Long value) {
            addCriterion("twoAgent =", value, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentNotEqualTo(Long value) {
            addCriterion("twoAgent <>", value, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentGreaterThan(Long value) {
            addCriterion("twoAgent >", value, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentGreaterThanOrEqualTo(Long value) {
            addCriterion("twoAgent >=", value, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentLessThan(Long value) {
            addCriterion("twoAgent <", value, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentLessThanOrEqualTo(Long value) {
            addCriterion("twoAgent <=", value, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentIn(List<Long> values) {
            addCriterion("twoAgent in", values, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentNotIn(List<Long> values) {
            addCriterion("twoAgent not in", values, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentBetween(Long value1, Long value2) {
            addCriterion("twoAgent between", value1, value2, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentNotBetween(Long value1, Long value2) {
            addCriterion("twoAgent not between", value1, value2, "twoagent");
            return (Criteria) this;
        }

        public Criteria andCountyagentIsNull() {
            addCriterion("countyAgent is null");
            return (Criteria) this;
        }

        public Criteria andCountyagentIsNotNull() {
            addCriterion("countyAgent is not null");
            return (Criteria) this;
        }

        public Criteria andCountyagentEqualTo(Long value) {
            addCriterion("countyAgent =", value, "countyagent");
            return (Criteria) this;
        }

        public Criteria andCountyagentNotEqualTo(Long value) {
            addCriterion("countyAgent <>", value, "countyagent");
            return (Criteria) this;
        }

        public Criteria andCountyagentGreaterThan(Long value) {
            addCriterion("countyAgent >", value, "countyagent");
            return (Criteria) this;
        }

        public Criteria andCountyagentGreaterThanOrEqualTo(Long value) {
            addCriterion("countyAgent >=", value, "countyagent");
            return (Criteria) this;
        }

        public Criteria andCountyagentLessThan(Long value) {
            addCriterion("countyAgent <", value, "countyagent");
            return (Criteria) this;
        }

        public Criteria andCountyagentLessThanOrEqualTo(Long value) {
            addCriterion("countyAgent <=", value, "countyagent");
            return (Criteria) this;
        }

        public Criteria andCountyagentIn(List<Long> values) {
            addCriterion("countyAgent in", values, "countyagent");
            return (Criteria) this;
        }

        public Criteria andCountyagentNotIn(List<Long> values) {
            addCriterion("countyAgent not in", values, "countyagent");
            return (Criteria) this;
        }

        public Criteria andCountyagentBetween(Long value1, Long value2) {
            addCriterion("countyAgent between", value1, value2, "countyagent");
            return (Criteria) this;
        }

        public Criteria andCountyagentNotBetween(Long value1, Long value2) {
            addCriterion("countyAgent not between", value1, value2, "countyagent");
            return (Criteria) this;
        }

        public Criteria andCityagentIsNull() {
            addCriterion("cityAgent is null");
            return (Criteria) this;
        }

        public Criteria andCityagentIsNotNull() {
            addCriterion("cityAgent is not null");
            return (Criteria) this;
        }

        public Criteria andCityagentEqualTo(Long value) {
            addCriterion("cityAgent =", value, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentNotEqualTo(Long value) {
            addCriterion("cityAgent <>", value, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentGreaterThan(Long value) {
            addCriterion("cityAgent >", value, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentGreaterThanOrEqualTo(Long value) {
            addCriterion("cityAgent >=", value, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentLessThan(Long value) {
            addCriterion("cityAgent <", value, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentLessThanOrEqualTo(Long value) {
            addCriterion("cityAgent <=", value, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentIn(List<Long> values) {
            addCriterion("cityAgent in", values, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentNotIn(List<Long> values) {
            addCriterion("cityAgent not in", values, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentBetween(Long value1, Long value2) {
            addCriterion("cityAgent between", value1, value2, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentNotBetween(Long value1, Long value2) {
            addCriterion("cityAgent not between", value1, value2, "cityagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentIsNull() {
            addCriterion("provinceAgent is null");
            return (Criteria) this;
        }

        public Criteria andProvinceagentIsNotNull() {
            addCriterion("provinceAgent is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceagentEqualTo(Long value) {
            addCriterion("provinceAgent =", value, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentNotEqualTo(Long value) {
            addCriterion("provinceAgent <>", value, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentGreaterThan(Long value) {
            addCriterion("provinceAgent >", value, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentGreaterThanOrEqualTo(Long value) {
            addCriterion("provinceAgent >=", value, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentLessThan(Long value) {
            addCriterion("provinceAgent <", value, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentLessThanOrEqualTo(Long value) {
            addCriterion("provinceAgent <=", value, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentIn(List<Long> values) {
            addCriterion("provinceAgent in", values, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentNotIn(List<Long> values) {
            addCriterion("provinceAgent not in", values, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentBetween(Long value1, Long value2) {
            addCriterion("provinceAgent between", value1, value2, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentNotBetween(Long value1, Long value2) {
            addCriterion("provinceAgent not between", value1, value2, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andInstitutionIsNull() {
            addCriterion("institution is null");
            return (Criteria) this;
        }

        public Criteria andInstitutionIsNotNull() {
            addCriterion("institution is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutionEqualTo(Long value) {
            addCriterion("institution =", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionNotEqualTo(Long value) {
            addCriterion("institution <>", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionGreaterThan(Long value) {
            addCriterion("institution >", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionGreaterThanOrEqualTo(Long value) {
            addCriterion("institution >=", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionLessThan(Long value) {
            addCriterion("institution <", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionLessThanOrEqualTo(Long value) {
            addCriterion("institution <=", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionIn(List<Long> values) {
            addCriterion("institution in", values, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionNotIn(List<Long> values) {
            addCriterion("institution not in", values, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionBetween(Long value1, Long value2) {
            addCriterion("institution between", value1, value2, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionNotBetween(Long value1, Long value2) {
            addCriterion("institution not between", value1, value2, "institution");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(String value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(String value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(String value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(String value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(String value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(String value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLike(String value) {
            addCriterion("amount like", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotLike(String value) {
            addCriterion("amount not like", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<String> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<String> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(String value1, String value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(String value1, String value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("level like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("level not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNull() {
            addCriterion("payType is null");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNotNull() {
            addCriterion("payType is not null");
            return (Criteria) this;
        }

        public Criteria andPaytypeEqualTo(String value) {
            addCriterion("payType =", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotEqualTo(String value) {
            addCriterion("payType <>", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThan(String value) {
            addCriterion("payType >", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThanOrEqualTo(String value) {
            addCriterion("payType >=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThan(String value) {
            addCriterion("payType <", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThanOrEqualTo(String value) {
            addCriterion("payType <=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLike(String value) {
            addCriterion("payType like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotLike(String value) {
            addCriterion("payType not like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeIn(List<String> values) {
            addCriterion("payType in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotIn(List<String> values) {
            addCriterion("payType not in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeBetween(String value1, String value2) {
            addCriterion("payType between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotBetween(String value1, String value2) {
            addCriterion("payType not between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andViptypeIsNull() {
            addCriterion("vipType is null");
            return (Criteria) this;
        }

        public Criteria andViptypeIsNotNull() {
            addCriterion("vipType is not null");
            return (Criteria) this;
        }

        public Criteria andViptypeEqualTo(String value) {
            addCriterion("vipType =", value, "viptype");
            return (Criteria) this;
        }

        public Criteria andViptypeNotEqualTo(String value) {
            addCriterion("vipType <>", value, "viptype");
            return (Criteria) this;
        }

        public Criteria andViptypeGreaterThan(String value) {
            addCriterion("vipType >", value, "viptype");
            return (Criteria) this;
        }

        public Criteria andViptypeGreaterThanOrEqualTo(String value) {
            addCriterion("vipType >=", value, "viptype");
            return (Criteria) this;
        }

        public Criteria andViptypeLessThan(String value) {
            addCriterion("vipType <", value, "viptype");
            return (Criteria) this;
        }

        public Criteria andViptypeLessThanOrEqualTo(String value) {
            addCriterion("vipType <=", value, "viptype");
            return (Criteria) this;
        }

        public Criteria andViptypeLike(String value) {
            addCriterion("vipType like", value, "viptype");
            return (Criteria) this;
        }

        public Criteria andViptypeNotLike(String value) {
            addCriterion("vipType not like", value, "viptype");
            return (Criteria) this;
        }

        public Criteria andViptypeIn(List<String> values) {
            addCriterion("vipType in", values, "viptype");
            return (Criteria) this;
        }

        public Criteria andViptypeNotIn(List<String> values) {
            addCriterion("vipType not in", values, "viptype");
            return (Criteria) this;
        }

        public Criteria andViptypeBetween(String value1, String value2) {
            addCriterion("vipType between", value1, value2, "viptype");
            return (Criteria) this;
        }

        public Criteria andViptypeNotBetween(String value1, String value2) {
            addCriterion("vipType not between", value1, value2, "viptype");
            return (Criteria) this;
        }

        public Criteria andTopagentIsNull() {
            addCriterion("topAgent is null");
            return (Criteria) this;
        }

        public Criteria andTopagentIsNotNull() {
            addCriterion("topAgent is not null");
            return (Criteria) this;
        }

        public Criteria andTopagentEqualTo(String value) {
            addCriterion("topAgent =", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentNotEqualTo(String value) {
            addCriterion("topAgent <>", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentGreaterThan(String value) {
            addCriterion("topAgent >", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentGreaterThanOrEqualTo(String value) {
            addCriterion("topAgent >=", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentLessThan(String value) {
            addCriterion("topAgent <", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentLessThanOrEqualTo(String value) {
            addCriterion("topAgent <=", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentLike(String value) {
            addCriterion("topAgent like", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentNotLike(String value) {
            addCriterion("topAgent not like", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentIn(List<String> values) {
            addCriterion("topAgent in", values, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentNotIn(List<String> values) {
            addCriterion("topAgent not in", values, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentBetween(String value1, String value2) {
            addCriterion("topAgent between", value1, value2, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentNotBetween(String value1, String value2) {
            addCriterion("topAgent not between", value1, value2, "topagent");
            return (Criteria) this;
        }

        public Criteria andLevelweightIsNull() {
            addCriterion("levelWeight is null");
            return (Criteria) this;
        }

        public Criteria andLevelweightIsNotNull() {
            addCriterion("levelWeight is not null");
            return (Criteria) this;
        }

        public Criteria andLevelweightEqualTo(Long value) {
            addCriterion("levelWeight =", value, "levelweight");
            return (Criteria) this;
        }

        public Criteria andLevelweightNotEqualTo(Long value) {
            addCriterion("levelWeight <>", value, "levelweight");
            return (Criteria) this;
        }

        public Criteria andLevelweightGreaterThan(Long value) {
            addCriterion("levelWeight >", value, "levelweight");
            return (Criteria) this;
        }

        public Criteria andLevelweightGreaterThanOrEqualTo(Long value) {
            addCriterion("levelWeight >=", value, "levelweight");
            return (Criteria) this;
        }

        public Criteria andLevelweightLessThan(Long value) {
            addCriterion("levelWeight <", value, "levelweight");
            return (Criteria) this;
        }

        public Criteria andLevelweightLessThanOrEqualTo(Long value) {
            addCriterion("levelWeight <=", value, "levelweight");
            return (Criteria) this;
        }

        public Criteria andLevelweightIn(List<Long> values) {
            addCriterion("levelWeight in", values, "levelweight");
            return (Criteria) this;
        }

        public Criteria andLevelweightNotIn(List<Long> values) {
            addCriterion("levelWeight not in", values, "levelweight");
            return (Criteria) this;
        }

        public Criteria andLevelweightBetween(Long value1, Long value2) {
            addCriterion("levelWeight between", value1, value2, "levelweight");
            return (Criteria) this;
        }

        public Criteria andLevelweightNotBetween(Long value1, Long value2) {
            addCriterion("levelWeight not between", value1, value2, "levelweight");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mp_num
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mp_num
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}