package com.battcn.entity;

import java.math.BigDecimal;

public class Reward {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_reward.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_reward.agentId
     *
     * @mbggenerated
     */
    private String agentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_reward.institutionId
     *
     * @mbggenerated
     */
    private BigDecimal institutionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_reward.firstAgent
     *
     * @mbggenerated
     */
    private BigDecimal firstagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_reward.secondAgent
     *
     * @mbggenerated
     */
    private BigDecimal secondagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_reward.member
     *
     * @mbggenerated
     */
    private BigDecimal member;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_reward.referee
     *
     * @mbggenerated
     */
    private BigDecimal referee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_reward.id
     *
     * @return the value of t_mp_reward.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_reward.id
     *
     * @param id the value for t_mp_reward.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_reward.agentId
     *
     * @return the value of t_mp_reward.agentId
     *
     * @mbggenerated
     */
    public String getAgentid() {
        return agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_reward.agentId
     *
     * @param agentid the value for t_mp_reward.agentId
     *
     * @mbggenerated
     */
    public void setAgentid(String agentid) {
        this.agentid = agentid == null ? null : agentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_reward.institutionId
     *
     * @return the value of t_mp_reward.institutionId
     *
     * @mbggenerated
     */
    public BigDecimal getInstitutionid() {
        return institutionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_reward.institutionId
     *
     * @param institutionid the value for t_mp_reward.institutionId
     *
     * @mbggenerated
     */
    public void setInstitutionid(BigDecimal institutionid) {
        this.institutionid = institutionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_reward.firstAgent
     *
     * @return the value of t_mp_reward.firstAgent
     *
     * @mbggenerated
     */
    public BigDecimal getFirstagent() {
        return firstagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_reward.firstAgent
     *
     * @param firstagent the value for t_mp_reward.firstAgent
     *
     * @mbggenerated
     */
    public void setFirstagent(BigDecimal firstagent) {
        this.firstagent = firstagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_reward.secondAgent
     *
     * @return the value of t_mp_reward.secondAgent
     *
     * @mbggenerated
     */
    public BigDecimal getSecondagent() {
        return secondagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_reward.secondAgent
     *
     * @param secondagent the value for t_mp_reward.secondAgent
     *
     * @mbggenerated
     */
    public void setSecondagent(BigDecimal secondagent) {
        this.secondagent = secondagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_reward.member
     *
     * @return the value of t_mp_reward.member
     *
     * @mbggenerated
     */
    public BigDecimal getMember() {
        return member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_reward.member
     *
     * @param member the value for t_mp_reward.member
     *
     * @mbggenerated
     */
    public void setMember(BigDecimal member) {
        this.member = member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_reward.referee
     *
     * @return the value of t_mp_reward.referee
     *
     * @mbggenerated
     */
    public BigDecimal getReferee() {
        return referee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_reward.referee
     *
     * @param referee the value for t_mp_reward.referee
     *
     * @mbggenerated
     */
    public void setReferee(BigDecimal referee) {
        this.referee = referee;
    }
}