package com.battcn.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class SubsidyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    public SubsidyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTwoagentIsNull() {
            addCriterion("twoAgent is null");
            return (Criteria) this;
        }

        public Criteria andTwoagentIsNotNull() {
            addCriterion("twoAgent is not null");
            return (Criteria) this;
        }

        public Criteria andTwoagentEqualTo(BigDecimal value) {
            addCriterion("twoAgent =", value, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentNotEqualTo(BigDecimal value) {
            addCriterion("twoAgent <>", value, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentGreaterThan(BigDecimal value) {
            addCriterion("twoAgent >", value, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("twoAgent >=", value, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentLessThan(BigDecimal value) {
            addCriterion("twoAgent <", value, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("twoAgent <=", value, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentIn(List<BigDecimal> values) {
            addCriterion("twoAgent in", values, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentNotIn(List<BigDecimal> values) {
            addCriterion("twoAgent not in", values, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("twoAgent between", value1, value2, "twoagent");
            return (Criteria) this;
        }

        public Criteria andTwoagentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("twoAgent not between", value1, value2, "twoagent");
            return (Criteria) this;
        }

        public Criteria andCountryagentIsNull() {
            addCriterion("countryAgent is null");
            return (Criteria) this;
        }

        public Criteria andCountryagentIsNotNull() {
            addCriterion("countryAgent is not null");
            return (Criteria) this;
        }

        public Criteria andCountryagentEqualTo(BigDecimal value) {
            addCriterion("countryAgent =", value, "countryagent");
            return (Criteria) this;
        }

        public Criteria andCountryagentNotEqualTo(BigDecimal value) {
            addCriterion("countryAgent <>", value, "countryagent");
            return (Criteria) this;
        }

        public Criteria andCountryagentGreaterThan(BigDecimal value) {
            addCriterion("countryAgent >", value, "countryagent");
            return (Criteria) this;
        }

        public Criteria andCountryagentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("countryAgent >=", value, "countryagent");
            return (Criteria) this;
        }

        public Criteria andCountryagentLessThan(BigDecimal value) {
            addCriterion("countryAgent <", value, "countryagent");
            return (Criteria) this;
        }

        public Criteria andCountryagentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("countryAgent <=", value, "countryagent");
            return (Criteria) this;
        }

        public Criteria andCountryagentIn(List<BigDecimal> values) {
            addCriterion("countryAgent in", values, "countryagent");
            return (Criteria) this;
        }

        public Criteria andCountryagentNotIn(List<BigDecimal> values) {
            addCriterion("countryAgent not in", values, "countryagent");
            return (Criteria) this;
        }

        public Criteria andCountryagentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("countryAgent between", value1, value2, "countryagent");
            return (Criteria) this;
        }

        public Criteria andCountryagentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("countryAgent not between", value1, value2, "countryagent");
            return (Criteria) this;
        }

        public Criteria andCityagentIsNull() {
            addCriterion("cityAgent is null");
            return (Criteria) this;
        }

        public Criteria andCityagentIsNotNull() {
            addCriterion("cityAgent is not null");
            return (Criteria) this;
        }

        public Criteria andCityagentEqualTo(BigDecimal value) {
            addCriterion("cityAgent =", value, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentNotEqualTo(BigDecimal value) {
            addCriterion("cityAgent <>", value, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentGreaterThan(BigDecimal value) {
            addCriterion("cityAgent >", value, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cityAgent >=", value, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentLessThan(BigDecimal value) {
            addCriterion("cityAgent <", value, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cityAgent <=", value, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentIn(List<BigDecimal> values) {
            addCriterion("cityAgent in", values, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentNotIn(List<BigDecimal> values) {
            addCriterion("cityAgent not in", values, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cityAgent between", value1, value2, "cityagent");
            return (Criteria) this;
        }

        public Criteria andCityagentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cityAgent not between", value1, value2, "cityagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentIsNull() {
            addCriterion("provinceAgent is null");
            return (Criteria) this;
        }

        public Criteria andProvinceagentIsNotNull() {
            addCriterion("provinceAgent is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceagentEqualTo(BigDecimal value) {
            addCriterion("provinceAgent =", value, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentNotEqualTo(BigDecimal value) {
            addCriterion("provinceAgent <>", value, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentGreaterThan(BigDecimal value) {
            addCriterion("provinceAgent >", value, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("provinceAgent >=", value, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentLessThan(BigDecimal value) {
            addCriterion("provinceAgent <", value, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("provinceAgent <=", value, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentIn(List<BigDecimal> values) {
            addCriterion("provinceAgent in", values, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentNotIn(List<BigDecimal> values) {
            addCriterion("provinceAgent not in", values, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("provinceAgent between", value1, value2, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andProvinceagentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("provinceAgent not between", value1, value2, "provinceagent");
            return (Criteria) this;
        }

        public Criteria andOnemerchantIsNull() {
            addCriterion("oneMerchant is null");
            return (Criteria) this;
        }

        public Criteria andOnemerchantIsNotNull() {
            addCriterion("oneMerchant is not null");
            return (Criteria) this;
        }

        public Criteria andOnemerchantEqualTo(BigDecimal value) {
            addCriterion("oneMerchant =", value, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantNotEqualTo(BigDecimal value) {
            addCriterion("oneMerchant <>", value, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantGreaterThan(BigDecimal value) {
            addCriterion("oneMerchant >", value, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("oneMerchant >=", value, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantLessThan(BigDecimal value) {
            addCriterion("oneMerchant <", value, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantLessThanOrEqualTo(BigDecimal value) {
            addCriterion("oneMerchant <=", value, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantIn(List<BigDecimal> values) {
            addCriterion("oneMerchant in", values, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantNotIn(List<BigDecimal> values) {
            addCriterion("oneMerchant not in", values, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("oneMerchant between", value1, value2, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andOnemerchantNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("oneMerchant not between", value1, value2, "onemerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantIsNull() {
            addCriterion("twoMerchant is null");
            return (Criteria) this;
        }

        public Criteria andTwomerchantIsNotNull() {
            addCriterion("twoMerchant is not null");
            return (Criteria) this;
        }

        public Criteria andTwomerchantEqualTo(BigDecimal value) {
            addCriterion("twoMerchant =", value, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantNotEqualTo(BigDecimal value) {
            addCriterion("twoMerchant <>", value, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantGreaterThan(BigDecimal value) {
            addCriterion("twoMerchant >", value, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("twoMerchant >=", value, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantLessThan(BigDecimal value) {
            addCriterion("twoMerchant <", value, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantLessThanOrEqualTo(BigDecimal value) {
            addCriterion("twoMerchant <=", value, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantIn(List<BigDecimal> values) {
            addCriterion("twoMerchant in", values, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantNotIn(List<BigDecimal> values) {
            addCriterion("twoMerchant not in", values, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("twoMerchant between", value1, value2, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTwomerchantNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("twoMerchant not between", value1, value2, "twomerchant");
            return (Criteria) this;
        }

        public Criteria andTopagentIsNull() {
            addCriterion("topAgent is null");
            return (Criteria) this;
        }

        public Criteria andTopagentIsNotNull() {
            addCriterion("topAgent is not null");
            return (Criteria) this;
        }

        public Criteria andTopagentEqualTo(BigDecimal value) {
            addCriterion("topAgent =", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentNotEqualTo(BigDecimal value) {
            addCriterion("topAgent <>", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentGreaterThan(BigDecimal value) {
            addCriterion("topAgent >", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("topAgent >=", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentLessThan(BigDecimal value) {
            addCriterion("topAgent <", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("topAgent <=", value, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentIn(List<BigDecimal> values) {
            addCriterion("topAgent in", values, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentNotIn(List<BigDecimal> values) {
            addCriterion("topAgent not in", values, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("topAgent between", value1, value2, "topagent");
            return (Criteria) this;
        }

        public Criteria andTopagentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("topAgent not between", value1, value2, "topagent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mp_subsidy
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}